### ISSUE TITLE
[Performance] Bids and Domains take a very long (>5mins) time to load

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#100]
This user owns a high number of tlds and is noting that it can take >5mins to go from this state:

![Screen Shot 2020-03-09 at 2 28 08 PM](https://user-images.githubusercontent.com/8230144/76259372-b5f6b880-6212-11ea-903d-d8542fe676ed.png)

to this state:
![Screen Shot 2020-03-09 at 2 29 51 PM](https://user-images.githubusercontent.com/8230144/76259366-b3945e80-6212-11ea-8dd8-d7235b7e17f4.png)

throughout all this, one can't look at their existing domains.
![Screen Shot 2020-03-09 at 2 29 38 PM](https://user-images.githubusercontent.com/8230144/76259369-b4c58b80-6212-11ea-9ca7-2d769b9e5ee0.png)

Can we speed this up by caching some data locally, or do some sort of progressive loading where individual UI elements are still accessible?  If the latter, a user can make changes even if bid status is not fully loaded for all names.

**Comment by mslipper** [comment]
May be an issue with `hsd`.

**Comment by pinheadmz** [comment]
I'm looking into this now. It might be nice to have pagination functions in the hsd wallet. There is some work in this area in bcoin that was never reviewed: https://github.com/bcoin-org/bcoin/pull/605

A work around for now might be to somehow abort API calls when the user clicks anything during a "loading" state. Might look into queuing up those calls for these views and allowing the queue processing to be cancelled.

**Comment by pinheadmz** [comment]
...not to mention every single name in the bids table calls `getNameInfo()` twice: once in the `BidStatus` component and once again in the same table row on the `BidTimeLeft` component...
