### ISSUE TITLE
[Bug] Domain Management When updating domain name records I lose logged in state

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#101]
Bob may be randomly losing logged in state when updating names.

Expected behavior: it should be possible to continue updating without needing to log back in.  
Current behavior: the reporting user get the following error after updating a handful of text records.

**This issue really slows down the name update / domain management process, combined with #100 (related), it makes Bob basically unusable for this use case (managing names) beyond 1-2 names as one has to continue to close the app, re-load all bids, and publish more updates**

![Screen Shot 2020-03-09 at 2 25 05 PM](https://user-images.githubusercontent.com/8230144/76258980-dd995100-6211-11ea-8a13-10da89e053b3.png)

**Comment by mslipper** [comment]
Duplicate #104.
