### ISSUE TITLE
Display error messages from the main process

### ISSUE THREAD

**Issue by mslipper** [kyokan/bob-wallet#107]
Currently, errors surfaced from the main process don't display actual error message. We should change this: errors from the main process should render the error message.

This can be implemented by sending an error object rather than a concatenated string on errors in the RPC layer.

**Comment by pinheadmz** [comment]
fixed already in https://github.com/kyokan/bob-wallet/commit/a34eec67dc2ac05fa5a86d482a2baa0e760c7eea#diff-f77729c1f44c5ca04a4759ab7f7628dbL74
