### ISSUE TITLE
Investigate supporting HSD workers and native bcrypto

### ISSUE THREAD

**Issue by mslipper** [kyokan/bob-wallet#109]
Currently, Bob runs HSD in in single-worker mode without bcrypto, which makes synchronizing the full blockchain take ages already. Ideally we should use HSD with multiple workers and the native backend.

**Comment by mslipper** [comment]
Investigate, time box to a day or two.

**Comment by pinheadmz** [comment]
I removed the backend==js from hsdMain.js and added a console log to bcrypto to confirm -- I was able to launch Bob in dev mode with native bcrypto just fine. Is it possible it's just a Windows issue? Or more likely, when Bob is compiled for multiple platforms the bcrypto addons _also_ need to be compiled cross-platform.

**Comment by pinheadmz** [comment]
Closing this now that #122 is merged. Will keep #123 open and check in every 10,000 blocks or so to see if workers actually improve performance. HSD issue https://github.com/handshake-org/hsd/issues/423 may bear fruit in the next few months as well.
