### ISSUE TITLE
Package security

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#114]
See https://github.com/bcoin-org/bcoin/issues/905

and:

```
$ npm audit
...
found 434 vulnerabilities (427 low, 4 moderate, 3 high) in 14496 scanned packages
  run `npm audit fix` to fix 411 of them.
  1 vulnerability requires semver-major dependency updates.
  22 vulnerabilities require manual review. See the full report for details.
```

We need to be extremely careful with dependencies since this application involves security, money, privacy, and cryptography. We shouldn't allow for dependency attacks which are rampant in the crypto ecosystem and especially with JS modules. The fact that we use react and redux with all their sub-dependencies exposes us to some risk.

I'm not sure the best course of action but we may want to consider git-committing `node_modules`.

**Comment by brandondees** [comment]
AFAIK the content integrity checks in the lock file should suffice, but either way we're presuming that the release authors are vetting all the dependencies of each release for trustworthiness. dependabot and other tools along those lines can help a good bit with at least keeping known vulnerabilities patched up, and should also catch known malware updates if/when they happen, but ultimately to ship a trustable app somebody's going to have to review the diffs of all the dependencies when updating them.

**Comment by rithvikvibhu** [comment]
Recently (v1, v2) we've tried to remove as many dependencies as possible but with the way the project is, there will always be external deps. Electron itself releases a new **major** version evey 4 weeks. And we _have_ to update it to stay on top of security fixes (almost all major updates have them!), etc. So I don't think we can vendor in / commit node_modules, that's gonna blow up the repo size.

For what it's worth, before every release, I do go through each package's release notes (and if possible, the code) to look for obvious malicous code / breaking changes / security notices. I know this isn't ideal, but unless there's a rewrite - with say Tauri like in #391, this is the only thing we can do.
