### ISSUE TITLE
[Suggestion, UX] "Processing" Indicators

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#115]
- It can be quite hard to tell if Bob is stuck/experiencing a bug, or simply working as intended and taking awhile.  This is especially true on slower computers.
- Suggestion: some kind of indicator on the top nav, cursor, or 'button state' progression that shows work is being done, so the user can contrast that with a bug / the need to re-start.
- Note: this was noticed when resetting my wallet - it hung for awhile and I wasn't sure if we should re-set it.

----

- While I work at Kyokan, please triage these issues (and all new ones from me from now on) as if they were coming from a regular user.

**Comment by tynes** [comment]
A quick thought on this, maybe a wrapper around any HTTP calls that toggles on during the HTTP call and off when it completes, this could trigger something on the UI. A user recently had trouble with HTTP calls timing out on their machine, so I added a `timeout` option to `hs-client` here:
https://github.com/handshake-org/hs-client/commit/db1ce860e44ba6c1dc8dcbe97e8f79c2f111f4c7. This could be turned way up for Bob.

**Comment by rithvikvibhu** [comment]
Long operations (rescan, loading transactions, etc.) have loading indicators now.
