### ISSUE TITLE
Sending TLDs

### ISSUE THREAD

**Issue by cyborg37** [kyokan/bob-wallet#132]
I had my TLD sent to my HNS wallet managed via Bob Wallet. Will it be possible to send out my TLD from Bob Wallet in the near future?

**Comment by pinheadmz** [comment]
Yes but probably not in the next release (v1.0)
We can set a goal to include this in v2.0

Until then, you can use the CLI with Bob:

https://forum.kyokan.io/t/guide-using-the-handshake-cli-with-bob/21

Transfer the name with this RPC command:

https://hsd-dev.org/api-docs/#sendtransfer

Then after two days you must finalize the transfer with this RPC command:

https://hsd-dev.org/api-docs/#sendfinalize

**Comment by mslipper** [comment]
This is coming in the next release.
