### ISSUE TITLE
Lots of names in watchlist seem stuck on "loading"

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#135]
![Screen Shot 2020-05-08 at 7 03 58 PM](https://user-images.githubusercontent.com/2084648/81455954-c9fd5e80-915e-11ea-9bee-ad9623ba2362.png)

Will need to dig this one out too, not sure what happened there.

**Comment by mslipper** [comment]
Maybe there were some HSD API changes?
