### ISSUE TITLE
Transaction stuck in pending for over 10 hours

### ISSUE THREAD

**Issue by 301gene** [kyokan/bob-wallet#138]
Describe the bug
After sending some HNS from Bob Wallet to Namebase.io, a tx was generated as usual, but has been stuck in pending for over 10 hours now. When I look it up on HNScan, the following message appears: "Looks your connection to a node is offline. Want to try a different network?".

https://hnscan.com/tx/70a1466c5970339f468852a6c798091ee66ebc482e2ce5ab9477ede92da5fcc8

To Reproduce

Generate an address on Namebase.io, send to that address from Bob Wallet.

Desktop (please complete the following information):

Windows 10
Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by pinheadmz** [comment]
@301gene I think we discussed this on Telegram, are you still having an issue or can we close this?

**Comment by 301gene** [comment]
Yes, the issue has been resolved. Successfully zapped the pending transaction!

**Comment by viteshan** [comment]
Same issue here. How did you solve this ? @301gene @pinheadmz

**Comment by 301gene** [comment]
@viteshan I used this CLI command guide to zap the transaction. Good luck!

https://forum.kyokan.io/t/guide-using-the-handshake-cli-with-bob/21
https://hsd-dev.org/api-docs/?shell--cli#zap-transactions

**Comment by pinheadmz** [comment]
Since version 3.0 Bob has a "delete unconfirmed transactions" button in settings

**Comment by viteshan** [comment]
> Since version 3.0 Bob has a "delete unconfirmed transactions" button in settings

I am worried that this transaction will be confirmed, after I delete it.

**Comment by viteshan** [comment]
Is there any way to resend this transaction?

**Comment by viteshan** [comment]
thanks @pinheadmz @301gene 
I resend the pending transaction by CLI command. and it's confirmed now.
https://forum.kyokan.io/t/guide-using-the-handshake-cli-with-bob/21
https://hsd-dev.org/api-docs/?shell--cli#wallet-resend
