### ISSUE TITLE
v0.2.9-rc.1 - 'image not found' on startup

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#141]
I replaced previous ver of Bob (0.2.8) and I do not have other instances of hsd running.

I get the following error on first run (see screencap below).

## Steps to Reproduce
-

## Context (Environment)
Mojave 10.14.6

## Logs
-

## Screencap
![Screen Shot 2020-05-26 at 4 32 13 PM](https://user-images.githubusercontent.com/8230144/82960193-9ef07880-9f6e-11ea-9ba4-867bc9174481.png)

**Comment by stanzo89** [comment]
Same issue on my end. Upgraded to the newest release and got the same error prompt

**Comment by mslipper** [comment]
Fixed in rc.2.
