### ISSUE TITLE
Windows build issues

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#142]
I'm a novice at Windows dev so I'm gonna just write a log of what I tried and see if I'm missing something obvious.

Windows 10
node 12.6.3
npm 6.14.4
git 2.26.2.windows.1

First this oddity on master branch, just one commit ahead of 0.2.9-rc2

362e3f5f602f3b7d15d30a16c643d95478081454

```
$ git checkout master 
$ rm -rf node_modules/
$ npm i
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\hsd\bcrypto@git+https:\github.com\bcoin-org\bcrypto.git#5c3e2b8b3f79d13e1b5c26be197708d0b9e5bcf9" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\turnt\AppData\Roaming\npm-cache\_logs\2020-06-05T17_35_28_000Z-debug.log
```

Next I checked out the release candidate directly:

120bd8f28205f89ef3c14a4e30222eaa5a05def7

```
$ git checkout tags/v0.2.9-rc.2
$ rm -rf node_modules/
$ npm i
```

This install runs fine, but threw this error when I tried run dev mode:

```
$ npm run dev
```

Windows pop up dialog:

```
An error occurred that prevented Bob from starting. Please quit and try again.

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\turnt\Desktop\work\bob-wallet\node_modules\bcrypto\build\Release\bcrypto.node
Stack: Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\turnt\Desktop\work\bob-wallet\node_modules\bcrypto\build\Release\bcrypto.node
    at process.func (electron/js2c/asar.js:155:31)
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:155:31)
    at Object.func [as .node] (electron/js2c/asar.js:155:31)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (C:\Users\turnt\Desktop\work\bob-wallet\node_modules\loady\lib\loady.js:98:17)
```

Finally tried an even older commit when `hsd` was still pinned to a pinheadmz branch:

8d7698e481b4beb92ff3e283ae0696daa9361dcf

```
$ git checkout 8d7698e481b4beb92ff3e283ae0696daa9361dcf
$ rm -rf node_modules
$ npm i
$ npm run dev
```

Results in the same windows DLL error.

Also just to note that downloading the rc2 binary from github runs FINE as far as I can tell, albiet a bit slow wihtout the native crytpo...

**Comment by pinheadmz** [comment]
Also getting this error trying to install on Ubuntu LTS also:

```
npm ERR! Could not install from "node_modules\hsd\bcrypto@git+https:\github.com\bcoin-org\bcrypto.git#5c3e2b8b3f79d13e1b5c26be197708d0b9e5bcf9" as it does not contain a package.json file.
```

**Comment by mslipper** [comment]
This is the Windows issue preventing the app from using native bindings on Windows. I'm not sure how best to fix this - maybe JJ would?

**Comment by GarrettBlackmon** [comment]
I encountered the same error in the first part of @pinheadmz's post when attempting to run ```npm i``` after pulling 362e3f5.

checking out 120bd8f then running ```npm i``` completed the install process and I was able to run the dev server on Manjaro Linux.

it looks like the first issue is caused by the addition of `bcrypto@` in package-lock.json on 362e3f5
```
"bcrypto": "bcrypto@git+https://github.com/bcoin-org/bcrypto.git#5c3e2b8b3f79d13e1b5c26be197708d0b9e5bcf9",
```

for readers experiencing the first issue

```
npm ERR! Could not install from "node_modules\hsd\bcrypto@git+https:\github.com\bcoin-org\bcrypto.git#5c3e2b8b3f79d13e1b5c26be197708d0b9e5bcf9" as it does not contain a package.json file.
```

run 
```
$ rm package-lock.json
$ rm -rf node_modules
$ npm i
```
and it should build for you.

**Comment by brandondees** [comment]
I also get this issue on linux. Removing the package-lock.json shouldn't ever be necessary, but given the stage of development I'll consider trying that.

**Comment by rithvikvibhu** [comment]
This is a pretty old issue (almost 2 years) and binaries for Windows are now built with GitHub Actions, so closing this for now.
