### ISSUE TITLE
Windows: help menu is electron stuff

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#143]
![image](https://user-images.githubusercontent.com/2084648/83910525-ba127380-a738-11ea-8509-3b6cfea7445a.png)

Also can't seem to find the version we added in #124 but I think part of that PR was understanding that it would only apply to OSX?

**Comment by rithvikvibhu** [comment]
On non-macos, it looks fine I think:
- File -> Close
- View -> Toggle Full Screen
- Help -> About Bob, Report an Issue

There's code specific to macos that's different and with more items (can't test it though): https://github.com/kyokan/bob-wallet/blob/master/app/menu.js

Can we close if it's fine? (didn't see any electron links)

**Comment by rithvikvibhu** [comment]
Closed by #481.
