### ISSUE TITLE
[Bug] - Bid Dates always a single value

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#144]
I've checked 3 auctions that are still in reveal: `inan`, `ihn`, and `0i`.

Dates always look like this: `01/19/70`
![Screen Shot 2020-06-13 at 7 17 20 PM](https://user-images.githubusercontent.com/8230144/84583170-925f8300-adaa-11ea-9bc6-0fdfb80290ec.png)

**Comment by panpansh** [comment]
same and more : 
![image](https://user-images.githubusercontent.com/790586/94344315-b3c54180-001e-11eb-8c2a-d69cec5ba843.png)

**Comment by rithvikvibhu** [comment]
The main issue seems to have been fixed a while ago. And the second issue fixed in 290
