### ISSUE TITLE
Timeout error on Bob UI

### ISSUE THREAD

**Issue by jacobjonz** [kyokan/bob-wallet#145]
Encountered a timeout error on opening Bob UI on Windows 10.

The debug file was still getting populated. 
(I had it running like that without realizing that it was still there.)

So, some the error messages I have from the log could be from later.
(The timestamps are the first time that type of error is encountered in that log)

In the log file, there were 10 types of error messages. Posting one of each type below.

Line 1215: [D:2020-06-12T02:46:34Z] (net) Error: Socket Error: ECONNRESET (173.255.209.126:12038)
Line 1260: [D:2020-06-12T02:46:39Z] (net) Error: Socket Error: ECONNREFUSED (45.79.108.139:12038)
Line 1266: [D:2020-06-12T02:46:42Z] (net) Error: Connection timed out. (138.68.224.26:12038)
Line 1292: [D:2020-06-12T02:46:43Z] (net) Error: Socket hangup. (96.126.101.79:12038)
Line 138699: Error: No DNS results.
Line 167308: [I:2020-06-14T21:18:42Z] (net) Error: Verification failure: invalid-covenant (code=invalid score=0 hash=...)
Line 167491: [D:2020-06-14T21:19:05Z] (net) Error: Peer is stalling (block). (172.104.214.189:12038)
Line 298217: [D:2020-06-16T03:48:44Z] (net) Error: Peer is stalling (verack). (45.79.134.225:12038)
Line 385502: [D:2020-06-16T12:35:14Z] (net) Error: Socket Error: EHOSTUNREACH (54.184.104.94:12038)
Line 433524: [I:2020-06-16T17:27:15Z] (net) Error: Verification failure: dust (code=nonstandard score=0 hash=...)

**Comment by jacobjonz** [comment]
Was able to recreate the issue.

This time, otehr than socket error and connection time out, the only other one is:

Line 521: [I:2020-06-17T20:12:36Z] (net) Error: Verification failure: invalid-covenant (code=invalid score=0 hash=...)

In the previous log, it was just one entry of this type.
In the current log file, I see 6 such entries with just 2 hash values altogether.

**Comment by rithvikvibhu** [comment]
Hey @jacobjonz, the `(net)` errors are normal as peers go offline regularly (when others close Bob, etc.)
As for the verification failure, any idea what you were trying to do at that time? I realize it's been 2 years :sweat_smile: but just in case. If not, then we can close this issue for now. Feel free to create a new one if it happens again!

It's mostly because a transaction was created incorrectly by Bob, but there haven't been any issues recently (at least didn't find any in my log file past few months).

**Comment by jacobjonz** [comment]
Hi Rithwik,
As you have noted, this is from long back. I don't remember exactly, but I believe this happened just on opening Bob.
Anyways, this is now a very old version and the issue may not be relevant anymore. I am closing it hence as you have suggested.
