### ISSUE TITLE
General Nit: Add description and about information for Bob Wallet on Github

### ISSUE THREAD

**Issue by smcki012** [kyokan/bob-wallet#149]
Right now when you look up "Bob Wallet" on Google, there is no description displayed for Bob Wallet indicating anywhere that it's a wallet GUI wrapper for HSD, nor that it can be used for auctions. Could you all add this information? I think it would aid more in the project's discovery...

[Screenshot](https://imgur.com/vqwk4m6)

**Comment by sdtsui** [comment]
I think this is resolved already, from looking at Google.

![Screen Shot 2020-07-06 at 7 42 48 PM](https://user-images.githubusercontent.com/8230144/86694921-eaac2e00-bfc0-11ea-9663-4372cb5d8f8f.png)
![Screen Shot 2020-07-06 at 7 42 33 PM](https://user-images.githubusercontent.com/8230144/86694926-eb44c480-bfc0-11ea-9636-251f02cdb4a2.png)

I've also updated the official "About" in the repo.

![Screen Shot 2020-07-06 at 7 42 27 PM](https://user-images.githubusercontent.com/8230144/86694928-ebdd5b00-bfc0-11ea-8334-485a666429d6.png)


Let me know if you have any other suggestions. Thank you, @smcki012
