### ISSUE TITLE
Improve: renew could ask for confirmation

### ISSUE THREAD

**Issue by Falci** [kyokan/bob-wallet#151]
## Expected Behavior
When performing some action that will expend money (even network fee), would be nice to be prompted with a confirmation message.

## Current Behavior
If you click, by mistake, on "Send renew", it just do it. No confirmation needed.

## Steps to Reproduce
1. Domain Manager
2. Select a domain
3. Click on "Send renew"

**Comment by brandondees** [comment]
I agree, but also would like the option to disable this.

**Comment by rithvikvibhu** [comment]
"Send Renew" asks for passphrase now. Does it count as a confirmation?

**Comment by rithvikvibhu** [comment]
Passphrase is needed for any transaction that involves spending (including renewals) and is a confirmation imo. Can reopen/discuss if anyone feels otherwise.

**Comment by Falci** [comment]
> "Send Renew" asks for passphrase now. Does it count as a confirmation?

Sorry. I missed this message.

Yes. Definitely, it solves the problem. Thanks!
