### ISSUE TITLE
[Feature] Portfolio View should `FINALIZE` txs correctly

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#154]
Current behavior:  `FINALIZE` transactions show up as 'Unknown'
![Screen Shot 2020-06-30 at 3 39 59 PM](https://user-images.githubusercontent.com/8230144/86184070-386bf680-bae8-11ea-801f-37034b92d7f8.png)

Desired Behavior:  we should display details similar to how we handle other name-related transactions.  For example:
"Finalized Winning Bid `${name}/`"

**Comment by pinheadmz** [comment]
Was this fixed in the recent rebase and merge?

**Comment by rithvikvibhu** [comment]
Finalized transactions show up correctly. After #296, even "finalized with payment" transactions show correct labels.
