### ISSUE TITLE
[UX] Better notification when seed phrase incorrect

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#155]
Better notification when seed phrase incorrect

 
## Expected Behavior
When my seed phrase is wrong, there should be text of some kind, or a guide/redirect back to the previous page to correct (with the box highlighted red). This or any number of other user-friendly notifications would be standard/expected.

## Current Behavior
Blue "create my wallet" button hangs for a few seconds at "Creating...", and then turns back to "Create my wallet", basically implying the user should click again.

## Steps to Reproduce

1.
1.
1.
1.

## Context (Environment)
0.3.0 - Windows

## Logs
n/a

## Screencap
did this on other computer and making this on windows, will do again on mac and post a screenshot after

**Comment by rithvikvibhu** [comment]
The flow now shows errors (if invalid seed phrase, words not in dictionary, etc.) and doesn't quit to the beginning anymore.
