### ISSUE TITLE
[Feature] Bids w/ Customizable Fee

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#156]
As of 0.3.0 we only support fee customization in Send View.
It should be straightforward to port the code to bid view or generalize it somehow when sending any transaction.

**Comment by mslipper** [comment]
This is unfortunately non-trivial, as the `hsd` RPC auction commands do not support setting the fee.

**Comment by pinheadmz** [comment]
TX fees using rpc should be configurable using https://hsd-dev.org/api-docs/#settxfee

**Comment by rithvikvibhu** [comment]
Dupe of #127, tracking there.
