### ISSUE TITLE
Wrong date format on auction page

### ISSUE THREAD

**Issue by Falci** [kyokan/bob-wallet#157]
## Expected Behavior
See the correct bid's date

## Current Behavior
Wrong/invalid date format:
![image](https://user-images.githubusercontent.com/1330573/86509621-9e5ac580-bde9-11ea-8600-ffc654194f36.png)

Note: it works fine in the Transaction History from Portfolio page
![image](https://user-images.githubusercontent.com/1330573/86509738-6011d600-bdea-11ea-971c-5e056c573c84.png)

## Steps to Reproduce
Go to any ongoing auction, check the bid dates

## Context (Environment)
macOS Catalina
Bob 0.3.0

**Comment by mslipper** [comment]
Duplicate #144.
