### ISSUE TITLE
[Feature] See auction after domain registered

### ISSUE THREAD

**Issue by Falci** [kyokan/bob-wallet#160]
For some reason, Bob doesn't show the auction information (bids & value) after the domain is registered (not sure why/when).

It would be interesting if that information could still be accessed, forever.

![image](https://user-images.githubusercontent.com/1330573/87234152-7a414a80-c3ce-11ea-8a2e-3c3f10975b85.png)

**Comment by brandondees** [comment]
Yeah I'd prefer this to have at least the same amount of info as namebase.

![image](https://user-images.githubusercontent.com/185732/88343322-acd53680-cd30-11ea-928c-23a7ffd21dd3.png)
