### ISSUE TITLE
[Feature] Show "Records" for any domain

### ISSUE THREAD

**Issue by Falci** [kyokan/bob-wallet#161]
I'd like to use Bob to visualise NS/TXT or any other record for any domain, even if I'm not the owner.
If I'm not the owner, it should be read-only, of course.

**Comment by pinheadmz** [comment]
Bob runs hsd and therefore has the usual hsd authoritiative nameserver running. I agree it might be cool to add this interface to Bob, but the data is available already if you need it:

(with Bob open)
```
dig @127.0.0.1 -p 5349 coolness
```

although this could collide with another HNS resolver on the same machine (https://github.com/kyokan/bob-wallet/issues/140)

...not to mention of course it's also accessible [with CLI](https://hsd-dev.org/api-docs/#getnameresource). But using DNS requests you don't need an API key.

**Comment by brandondees** [comment]
I'd also be happy to be able to "browse" this info in the GUI instead of having to remember dig flags.

**Comment by rithvikvibhu** [comment]
fyi, @Falci's PR is merged, can close?

**Comment by Falci** [comment]
Done in #283
