### ISSUE TITLE
Receiving  wallet address does not change after being used 

### ISSUE THREAD

**Issue by codaelux** [kyokan/bob-wallet#162]
The receiving wallet does not change after being used to receive HNS  this is not good for privacy 
## Expected Behavior

New address after previous has been used 
## Current Behavior

No new address is generated

**Comment by pinheadmz** [comment]
Hm, this is not my experience. In regtest I generated a block to the Bpb current receive address and the UI updated automatically -- although it took about 10 seconds.

There's a lot of things in Bob that are based on a 10-second (I think) poll loop that could eventually be replaced by websocket events for a very snappy, instantly-gratifying interface.

Is there anything special about your case? Like does it work for one incoming transaction type but not another?
