### ISSUE TITLE
Issues with bids of 0 value

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#163]
h/t @falci

Bob doesn't normally allow bids of `0` value, but this can be sidestepped by entering a value of `0.00000000001`:

https://github.com/kyokan/bob-wallet/blob/4c424a19580ababf08ac7b5bd22b92aebdd4c844/app/pages/Auction/BidActionPanel/BidNow.js#L189

This is one thing that should be fixed -- 6 decimal place max, as enforced here:

https://github.com/kyokan/bob-wallet/blob/65ae2106cf82624b240a2efd89cd269c85567074/app/pages/Auction/RepairBid.js#L58

The user can also use RPC calls to send a bid of `0`, which is totally valid **as long as the lockup is above the dust limit**

Unfortunately the `0` value is incorrectly interpreted as false in two places which both trigger repair bid, and prevent repair bid:

Incorrectly flagging a bid of `0` as missing (in need of repair -- this should just check for `undefined`):

https://github.com/kyokan/bob-wallet/blob/4c424a19580ababf08ac7b5bd22b92aebdd4c844/app/pages/Auction/BidActionPanel/BidNow.js#L411

Preventing value of `0` being entered as a repaired bid (this should just be a type check):

https://github.com/kyokan/bob-wallet/blob/65ae2106cf82624b240a2efd89cd269c85567074/app/pages/Auction/RepairBid.js#L62

**Comment by Falci** [comment]
My 2 cents about the bid value:
* If the network doesn't store the information, not even encoded, should Bob display it? (it seems a "privileged information")
* And the opposite: if it's an interesting information, shouldn't the network store it? Maybe encoded?

**Comment by pinheadmz** [comment]
The bids are not stored on the network because they are blind! That is the design of the system. Bob only displays YOUR bids because they are your secret, and they are also required for the REVEAL, when the bid value is actually plainly broadcast to the network. I have some ideas on how to make the bid value recoverable like the rest of the BIP44 scheme: https://github.com/handshake-org/hsd/issues/378#issuecomment-618486570

**Comment by brandondees** [comment]
Since this is electron we could use html5 input validation to make it even less accident prone, right? (I mean reference the same regex from the input, so nobody ever sees an error without using hacker methods, they can't even push the button till it's valid).

**Comment by pinheadmz** [comment]
@brandondees I'm not sure exactly what you mean, but I have written a patch for this already if you want to take a look:

https://github.com/kyokan/bob-wallet/pull/170

**Comment by rithvikvibhu** [comment]
Fix (#170) merged in Sep 2020, closing.
