### ISSUE TITLE
[Bug] Bob should prevent bid if the last block was already mined

### ISSUE THREAD

**Issue by Falci** [kyokan/bob-wallet#164]
(sorry for skipping the issue template)

This image is an example:
![image](https://user-images.githubusercontent.com/1330573/87761906-884dfb80-c812-11ea-8e71-bd5d02cc5d09.png)

Current block: 24287
Reveal period: 24288

The "Place bid" button is still active.
If I place a bid at this moment, in the best scenario, it will be added to the next block (24288) meaning it won't be a valid bid.

IMO, Bob should already show the "Review" CTA. Even if the auction is not in the reveal period yet, by the time the TX get added to the block, it will be valid.

**Comment by pinheadmz** [comment]
When you click "place bid" in this scenario, do you not get an error? hsd should check the state of the name *at current height + 1*:

https://github.com/handshake-org/hsd/blob/master/lib/wallet/wallet.js#L1668

Although I agree the Bob UI should also base its state on the *next* block instead of using the state as reported literally by `getnameinfo`

**Comment by brandondees** [comment]
I did this today and it gave me an error, something to the effect of "can't bid, already ended" but the button should be disabled at that point IMO. 

A followup issue is that bob seemingly won't allow a reveal attempt until 2 blocks later, when I would have assumed you could go ahead and submit the reveal on the same block that it became invalid to bid, or perhaps 1 block later. If it's a blockchain rule that's fine, I'd just like the UI to reflect what you can/cannot do accordingly.

ANOTHER followup/related issue is that when there's a bid pending, I can't attempt another bid, even though I might really want to (i.e. if a sniper bid appears in the mempool right after I submitted the bid, on the last block of bidding), without deleting all pending tx. It'd be nicer if I could just go ahead and bid as often as I want, perhaps with a little warning text about the pending ones and perhaps a confirmation click to avoid accidental double-tap bids. It would also be nice to be able to delete the pending tx more selectively by auction for the same purpose.

**Comment by pinheadmz** [comment]
> A followup issue is that bob seemingly won't allow a reveal attempt until 2 blocks later, when I would have assumed you could go ahead and submit the reveal on the same block that it became invalid to bid, or perhaps 1 block later. If it's a blockchain rule that's fine, I'd just like the UI to reflect what you can/cannot do accordingly.

This is the same off-by-one issue I think. Under the hood, hsd is aware that bids are invalid when the next block is the first REVEAL block, but Bob isn't: it relies on the property `namestate.state == BIDDING` for example. So I think it's the exact same thing with reveals: hsd knows you can reveal if the next block is the first REVEAL block, but Bob doesn't.




> ANOTHER followup/related issue is that when there's a bid pending, I can't attempt another bid, even though I might really want to (i.e. if a sniper bid appears in the mempool right after I submitted the bid, on the last block of bidding), without deleting all pending tx. It'd be nicer if I could just go ahead and bid as often as I want, perhaps with a little warning text about the pending ones and perhaps a confirmation click to avoid accidental double-tap bids. It would also be nice to be able to delete the pending tx more selectively by auction for the same purpose.

Definitely agree with this -- could you open up a new issue / feature request? I think an implementation would just need to prevent users from accidentally sending the same bid twice, so we need obvious feedback that their currently pending bid does not need to be re-sent, that "pending" is OK.

**Comment by Falci** [comment]
Should it be updated on HSD side? Maybe HSD should return `namestate.state == BIDDING` if the last block under the `OPEN` window was already mined.

**Comment by pinheadmz** [comment]
No, that's messing with consensus, and I'm pretty sure the hsd wallet is already hip to checking the state on `height + 1`:


https://github.com/handshake-org/hsd/blob/master/lib/wallet/wallet.js#L1668


We just need Bob to do this as well, instead of:

https://github.com/kyokan/bob-wallet/blob/4f4cc73ea7075fe04c1fd128e9bef6797fd86469/app/utils/nameHelpers.js#L52-L56

**Comment by brandondees** [comment]
yeah shouldn't take a lot of code to fix just needs to be a tad smarter about the edges.

@pinheadmz sure, will copy that into a new issue with cross linkage to get it started, lmk on the other side if it should be revised or anything.

**Comment by rithvikvibhu** [comment]
Fixed by #286, can probably close.
