### ISSUE TITLE
[Misc Linux Issues] Retry Issues on majority of on-chain interactions

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#172]
```
it may be just a linux issue or something about my unlocked dependencies but almost every interaction i get a timeout error and have to re-try one or more times before i see success. i'm thinking if that kind of issue is affecting more than just me, it might ultimately be important to restructure how the async work is handled in general. i think i would probably have a separate thread running a work queue to do all that stuff and re-tries and whatnot else, and make sure it never blocks the UI. introduce some visual feedback when relevant updates are pending and then it'd be a lot easier to tell when it's "thinking/waiting" vs "broken" vs "failed after re-try attempts, but try again"
```

from [@brandondees](https://github.com/brandondees) - will close when Linux is more stable.
if possible, please link to this issue as we make progress.

**Comment by sdtsui** [comment]
more info from brandon, thanks again for reporting
![Screen Shot 2020-07-23 at 9 45 22 AM](https://user-images.githubusercontent.com/8230144/88314102-4bc64800-ccc9-11ea-8f14-528b1ef835b2.png)

**Comment by brandondees** [comment]
Sorry for not posting this myself, it's because I wasn't sure about the project's issue policies and was being lazy. Will continue following up here.

**Comment by brandondees** [comment]
just re-quoting the initial message here for text wrapping

> it may be just a linux issue or something about my unlocked dependencies but almost every interaction i get a timeout error and have to re-try one or more times before i see success. i'm thinking if that kind of issue is affecting more than just me, it might ultimately be important to restructure how the async work is handled in general. i think i would probably have a separate thread running a work queue to do all that stuff and re-tries and whatnot else, and make sure it never blocks the UI. introduce some visual feedback when relevant updates are pending and then it'd be a lot easier to tell when it's "thinking/waiting" vs "broken" vs "failed after re-try attempts, but try again"

**Comment by rithvikvibhu** [comment]
@brandondees does it still happen with the latest versions? This issue is almost 2 years old and I haven't had these problems recently.

**Comment by brandondees** [comment]
i don't have a linux environment running currently but will check it out again whenever i get around to setting that back up. i'm guessing this is largely mitigated by now in the form of general performance improvements but might still not be fundamentally solved

**Comment by brandondees** [comment]
if you can run the compiled version and dev mode on linux without having major first sync issues, it's probably fine now, feel free to close
