### ISSUE TITLE
[Feature] Make it easy to find bids that are missing reveals.

### ISSUE THREAD

**Issue by brandondees** [kyokan/bob-wallet#173]
Currently the transaction history in the main/default view is really hard to navigate or use for anything other than checking the state of the most recent few transactions. The "Your Bids" view is more generally useful for bid followup, but it appears not to be sorted in any meaningful way, and it's not re-sortable to find bids by recency or status or anything like that. This list doesn't show the most actionable info about a bid/auction, such as whether it is pending or mined, confirmation count, or whether it has been revealed or has a pending reveal, whether it has been redeemed/registered, or whether there's a new lockup that potentially beats your last bid.

I'd like to be able to see all that info at a glance from the list view, if possible, but for sanity purposes I think it should at least highlight bids that need a followup action like reveal/redeem/register, or allow sorting them by that type of status. It'd be a lot nicer if you could just click a button straight from the list to go ahead and perform those actions without the extra navigation step (including reloading auction history etc).

**Comment by sdtsui** [comment]
linking to #174 - good starting point for any future redesign

**Comment by rithvikvibhu** [comment]
Breaking up this into points:
- Sort in Your Bids table - Tracking in #228
- Filter by auction status - Added in #363 
- Info for pending reveals, registers, redeems and actions on them - Added in #358

I think we can close this, reopen/discuss if I missed anything.
