### ISSUE TITLE
[Feature / UX] Display "spendable balance" on the top bar in all UI views

### ISSUE THREAD

**Issue by brandondees** [kyokan/bob-wallet#174]
Currently this info is visible in the gear menu but when actively managing bids across concurrent auctions, I want to refer to it pretty continuously. It'd save me a lot of mousing and clicking to just always show it in the top bar. Total balance is much less actionable so I don't really care about seeing it taking up the extra space, but the spendable balance is almost always relevant for me to be aware of.

**Comment by sdtsui** [comment]
good to flag for any future redesign question-thanks!

**Comment by rithvikvibhu** [comment]
`Spendable Balance` is already accessible in all pages (via the gear icon menu). But we can probably remove `Total Balance` as it's not really useful. Keeping the issue open until that is removed.
