### ISSUE TITLE
Cannot read property 'length' of null on app startup

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#181]
I believe we first started getting this issue on startup after merging #148  - I experienced this on dev but we were not able to reproduce, so went ahead and merged.

More users are experiencing this bug now - would like to ask if others can help us get to the bottom of this:

![photo_2020-07-27_16-22-16](https://user-images.githubusercontent.com/8230144/88601385-6a0fa900-d025-11ea-87cf-d33100df5c8f.jpg)

**To all Bob users, you could please react/emoji, comment on, or provide more information if you have encountered this exact startup bug?**

If possible, please specify any of the following information if you have it on hand:
- Bob version you have installed
- OS and version of that OS
- what kind of internet connection you are on, if you are okay with sharing
- Specify if it happens all of the time (basically preventing you from using the app), or only some of the time (it resolves after closing or resyncing).  If it happens all of the time, specify the last known time/version where it worked and anything else you might know about what you were doing before the bug began.

There appear to be plenty of people doing fine using it, especially on macOS, but we'd like to stay on top of this.

**Comment by Falci** [comment]
There's not that much [length](https://github.com/kyokan/bob-wallet/search?q=.length&type=Code) in the source.
We could add a safe validation before each of them, improving the error message.

I'd suggest to mark this a [good first issue](https://github.blog/2020-01-22-how-we-built-good-first-issues/)

**Comment by pinheadmz** [comment]
I think it's a race condition where Bob is asking the hsd node for some object like TX history, but the node has not completely started up yet, and there is no response.

**Comment by rithvikvibhu** [comment]
Is this still an issue? Never seen it before. If it's a race issue, I think Bob now waits for hsd to start, so shouldn't occur again.

**Comment by rithvikvibhu** [comment]
Closing this now, feel free to reopen or create a new issue if it occurs again.
