### ISSUE TITLE
Long names need better handling in UI

### ISSUE THREAD

**Issue by chikeichan** [kyokan/bob-wallet#195]
Most straightforward way would be to show ellipsis by default, and expand/collapse on click.

--------
> xn--0

![image](https://user-images.githubusercontent.com/1330573/89573287-ad8ac400-d82a-11ea-8f4c-49f2153142e8.png)

> what happens when strings get very long

![image](https://user-images.githubusercontent.com/1330573/89573536-0c503d80-d82b-11ea-8665-879480d17620.png)
![image](https://user-images.githubusercontent.com/1330573/89574294-32c2a880-d82c-11ea-9d73-0043cf4b861f.png)

This is the worst result I could get:
![image](https://user-images.githubusercontent.com/1330573/89574556-a4025b80-d82c-11ea-94e7-407c70e7dfea.png)

![image](https://user-images.githubusercontent.com/1330573/89573711-51746f80-d82b-11ea-8d8a-7ba43c52725f.png)
![image](https://user-images.githubusercontent.com/1330573/89574051-d495c580-d82b-11ea-9cb6-ef2fc4086d79.png)

_Originally posted by @Falci in https://github.com/kyokan/bob-wallet/pull/194#issuecomment-670151547_

**Comment by brandondees** [comment]
note that tlds can have length up to 63 chars. https://www.namebase.io/domains/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee can be used for handy reference. note that depending on font, other characters may be wider than `e` so just calibrating a width/size combo to a single example may not suffice. IMHO better to enable line wrapping, like what we see with the emoji part of the example above.
