### ISSUE TITLE
reserved name claims: bugs and missing features

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#198]
1) Feature request: add an interface to submit a reserved name CLAIM, and then indicate to the user that they can register after 30 days

2) Bug report: A user asked me for help. They are running Bob and we used CLI commands to create and send the CLAIM. 30 days later we used CLI to send the REGISTER and get the free money!

But, Bob has some kind of issue with the reserved name. The names appear in the "My Domains" screen, but when the user clicks a name, the screen goes blank and Bob needs to restart.

I will try to create a test scenario locally using some tricks to sneak fake reserved names into hsd and see if I can find the actual bug.

**Comment by sdtsui** [comment]
@chikeichan let's try to keep an eye on this one and get this in along with #121

**Comment by rithvikvibhu** [comment]
@pinheadmz did all the work :p (#357)
