### ISSUE TITLE
Dial to select block explorer in Settings

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#201]
@chikeichan

**Comment by sdtsui** [comment]
Users want to be able to use block explorers other than HNScan.  Note that the URL formats may be different for txs.
I'm thinking we start with Shakescan so there's at least a format for others to contribute.
https://shakescan.com/

**Comment by pinheadmz** [comment]
duplicate? https://github.com/kyokan/bob-wallet/issues/152
