### ISSUE TITLE
Set lookahead in Settings

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#203]
User should be able to adjust lookahead so their wallet can support more names/transactions.  Powerusers are asking for this as it looks as if stuff is disappearing from their wallets.

I think this should be a number input.  You might need to restart the node or at least kick off a rescan -> we could make this automatic or have another button for that.

**Comment by pinheadmz** [comment]
Disagree. Look ahead should be a standard. If users set it too low not knowing what it is, they shoot thenself in the foot. It also means they must memorize that number or keep it with their wallet seed if they ever import. I think it should not be user configurable. What we really need are deep wallet refractors in hsd. 

More: https://github.com/handshake-org/hsd/issues/407#issuecomment-668625559

**Comment by pinheadmz** [comment]
Disagree. Look ahead should be a standard. If users set it too low not knowing what it is, they shoot thenself in the foot. It also means they must memorize that number or keep it with their wallet seed if they ever import. I think it should not be user configurable. What we really need are deep wallet refractors in hsd. 

More: https://github.com/handshake-org/hsd/issues/407#issuecomment-668625559

**Comment by pinheadmz** [comment]
Disagree. Look ahead should be a standard. If users set it too low not knowing what it is, they shoot thenself in the foot. It also means they must memorize that number or keep it with their wallet seed if they ever import. I think it should not be user configurable. What we really need are deep wallet refractors in hsd. 

More: https://github.com/handshake-org/hsd/issues/407#issuecomment-668625559

**Comment by chikeichan** [comment]
did some digging into the rescan behavior and agree with @pinheadmz - a high enough fixed value with a rescan button should fix the problem, or at least give users to keep rescanning until they grabbed all their txs.

**Comment by chikeichan** [comment]
The issue I found with lookahead is that if the values is too high, it actually starts to behave inconsistently. I am guessing that the issue might have to do with size limit of bloom filter, if there is one.

The behavior i am noticing is that:
- I have a wallet with a lookahead value of 700
- if i set lookahead value to 500, i need to rescan twice
- if i set lookahead value to 700, i only need to rescan once
- if i set lookahead value to 800, i actually need to rescan twice as well 
- and if i set lookahead value beyond 1000, i start running into errors from wdb

**Comment by pinheadmz** [comment]
These two make sense:

> if i set lookahead value to 500, i need to rescan twice
> if i set lookahead value to 700, i only need to rescan once

This is a bit surprising:

> if i set lookahead value to 800, i actually need to rescan twice as well

This is kinda, eh maybe not surprising given the performance hit of generating and scanning for all those keys:

> and if i set lookahead value beyond 1000, i start running into errors from wdb

We may find that a lookahead of 1000 takes several seconds when creating a new account, and may cause race conditions when the wallet just isn't ready for API calls yet. I need to try some benchmarks with this value in hsd, but then yeah I think we either need to ditch the internal bloom filter (means rescans will take a lot longer) or refactor it so when a tx is found in a block, the filter is updated and that block is rescanned again: https://github.com/bcoin-org/bcoin/commit/c6859b347bd6989c1eb87fc58e05b6fcc4b91c8b

**Comment by chikeichan** [comment]
#232
