### ISSUE TITLE
[Feature] Redeem all method

### ISSUE THREAD

**Issue by ca98am79** [kyokan/bob-wallet#209]
Would be nice to have a way to redeem all bids at once, passing the `null` param into `sendRedeem`.  And possibly a setting to have this automatically happen

**Comment by sdtsui** [comment]
Thanks @ca98am79  - I haven't been able to get this to work in CLI it just blanks, otherwise I'd have 
Have you?  Could DM about it on Telegram.  I think we can plan to get this in after the v2.2.0 upgrade.
