### ISSUE TITLE
Observation: 0.4.0 unable to sync, 0.5.0 -- with walletnode process separated -- syncs smoothly

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#210]
Bug Report from a non-technical windows user.
I believe this is relevant to HSD as well, but we'll start by documenting here.
As outlined by @pinheadmz in [bcrypto/49](https://github.com/bcoin-org/bcrypto/issues/49), everything below is regarding windows -- in electron -- 6.0.7.

-------
-------

User has roughly the following specs:
```
Windows 10
OS build 18362.657
Installed Ram: 4.00GB (3.89 GB usable)
AMD A6-9220 Radeon
```

User uninstalled their previous version (0.3.0) and reinstalled a fresh instance of 0.4.0.
User had notably slow sync, which then froze at around 80% and stopped syncing.
User got advice from other users and developers to try different things, such as refreshing the app in electron context, or quitting/re-starting the app at various intervals. No change was observed - syncing remained stuck at 80%.

User uninstalled 0.4.0 and installed 0.5.0 - had a smooth sync of around 1hr to 100% as of 09/18.  As of the time of this issue, user has had no issues since.

While we aren't currently equipped to debug, it's an instance of a switch from the fullnode to walletnode+node, with no other configuration changes, enabling a user to successfully sync while previously unable to.

**Comment by rithvikvibhu** [comment]
Looks like there wasn't any issue after 0.5.0, closing. There have been a lot of changes to the node+wallet code now.
