### ISSUE TITLE
[Send Screen] Available Balance Issues

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#211]
We appear to be getting a different available balance (after hsd returns an error) than the required balance that the wallet is aware of.  Is it possible to (i) debug the wallet so it doesn't encounter these errors, or (ii) abstract this away from the user by making an un-sendable request to the node first, and simply displaying the available value as maximum?

![photo_2020-08-22_03-12-01](https://user-images.githubusercontent.com/8230144/90954001-4faecc80-e425-11ea-9504-bf9f882fdbd1.jpg)

This has been observed in both 0.4.0 and 0.5.0 by the same user.

**Comment by rithvikvibhu** [comment]
Lookahead-related issues have been resolved last year iirc. Closing this issue from 2020.
