### ISSUE TITLE
Mining payout appears as the full tx amount rather than the single output I received.

### ISSUE THREAD

**Issue by brandondees** [kyokan/bob-wallet#216]
## Expected Behavior
When I receive HNS, it should appear in the transactions log showing the amount received. In my case, it's something close to 10HNS for f2pool mining shares.
https://hnscan.com/tx/8cc078a9ccfb57ab4d3eb993769d41e6cd834892267fd6f8122bbeb058e7a33c

## Current Behavior
The transaction log shows the transaction, but the amount shown is the total of the transaction. 
![image](https://user-images.githubusercontent.com/185732/92335736-5a09d100-f089-11ea-933f-78a075483a09.png)
https://hnscan.com/tx/8cc078a9ccfb57ab4d3eb993769d41e6cd834892267fd6f8122bbeb058e7a33c

## Context (Environment)
Bob 0.5.0 built locally on arch linux

**Comment by brandondees** [comment]
Presuming this is related: I just sent some HNS to another wallet and notice that it shows as "Received Funds" instead of "Sent" although the amount is correct

**Comment by pinheadmz** [comment]
possibly duplicate issue: https://github.com/kyokan/bob-wallet/issues/217

**Comment by brandondees** [comment]
seems like it could be related but the label issue there is not applicable here. the issue is with the amount shown. in the above screenshot it shows i received 800kHNS but what I received is actually something like 10HNS from a single output (correctly, just not displayed so).

**Comment by pinheadmz** [comment]
the same function computes the label and value for each tx in bob: https://github.com/kyokan/bob-wallet/blob/0c89d808188003ce4438ad7317c8d7809d458231/app/ducks/walletActions.js#L268-L359

**Comment by rithvikvibhu** [comment]
I used to see this too, but must've been fixed. Checked my tx history and no crazy values anymore. (on v0.6.2)

**Comment by rithvikvibhu** [comment]
The single output value is shown now, was fixed in #268.
Can confirm, this amount was weird before, now it shows up correctly.

![image](https://user-images.githubusercontent.com/5113343/121812172-83910200-cc84-11eb-96d3-72bdddfc2c5f.png)
