### ISSUE TITLE
[documentation] Add docs for Linux Production build

### ISSUE THREAD

**Issue by pi0neerpat** [kyokan/bob-wallet#218]
## Issue

Linux users do not have much documentation in this repo, or online, and may not be familiar with Electron. The [dev contributing gist](https://gist.github.com/pinheadmz/314aed5123d29cb89bfc6a7db9f4d02e) from Matthew only describes running in development mode. It does not explain how to build + run in "production" mode.  Dev mode scary.

Here is what I would like to add. Please let me know if its wrong, I don't have much electron experience.

### Instructions for Linux installation

```bash
git clone https://github.com/kyokan/bob-wallet
cd bob-wallet; npm install
```

(optional) Test it works with

```bash
npm run dev
```

Now build the app package

```bash
npm run package-linux
``` 

The output app will be created in `/release` folder. Open the file called something like `Bob-0.5.0.AppImage` to start Bob Wallet!

**Comment by sdtsui** [comment]
Hey, thanks @pi0neerpat.  @brandondees as our resident Linux user, any comments?  As long as it says Linux is not officially supported, I don't mind a docs PR including this, anywhere really.

**Comment by brandondees** [comment]
Yep looks like what I've been doing

**Comment by pi0neerpat** [comment]
Cool beans. I made a PR for this
