### ISSUE TITLE
Latest 0.5.0 Stable does not start on macOS - Library not loaded (libgmp)

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#219]
<img width="412" alt="Screen Shot 2020-09-14 at 2 25 17 PM" src="https://user-images.githubusercontent.com/8230144/93143164-3d2e5880-f69c-11ea-9658-9bc7cbb77fee.png">

Observed by multiple macOS users, on:
- mojave 10.14.2
- high sierra 10.13.6

All users reporting this have found the `0.5.0-rc` (i.e. without dependency changes, just the walletnode separation) still works on their devices.

**Comment by mslipper** [comment]
Can you try downloading the 0.5.0 DMG from the releases page? I replaced it with one that I built on a system without GMP, which I believe may fix the issue.

**Comment by mansaj** [comment]
Issue seems to be fixed!
