### ISSUE TITLE
 issues with atomic swap

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#224]
Some quick notes as I start to play with this:

1) we need to ask for user wallet password when the buyer clicks "pay and transfer". Actually both buyer and seller need to enter passphrase when they sign their parts. We have this logic now I think:

```
await new Promise((resolve, reject) => {
  dispatch(getPassphrase(resolve, reject));
});
```

2) ~during one test round I got an "output is dust error" -- need to look into this. The name value was 0 (regtest, one-bidder auction) I really hope hsd doesn't have an issue with Finalize's being tested for dust...~ OK I think whats happening is I entered a swap price of `100` thinking that was in HNS, but its not, its in dollarydoos. And `0.000100` is below the dust limit...
3) the finalize with payment screen asks for the recipient for the name, this should already be known since the TRANSFER was sent to that name (must be the same name)

**Comment by mslipper** [comment]
Issues #2 should be fixed with latest release.

**Comment by pinheadmz** [comment]
@mslipper  I think I was able to address all these issues in this commit on my fork of Bob: https://github.com/pinheadmz/bob-wallet/commit/46587640e9023ca61b2c200fb1abb0940fcb2ce2

And one other which is how the price is displayed in the claim name with payment screen (I converted dollarydoos to HNS).

I don't think this commit will cherry-pick directly on to kyokan/bob master but I'll check it out next chance I get and open a PR. If you're in a rush you could probably port it over without my help.
