### ISSUE TITLE
Add an option to choose where to download node data

### ISSUE THREAD

**Issue by fuomag9** [kyokan/bob-wallet#260]
As per title, I'd like to choose where to download my node data instead of using `%AppData%\Roaming\Bob`

**Comment by pinheadmz** [comment]
Here's the patch I use for this: https://github.com/pinheadmz/bob-wallet/commit/44f5ba138306b08838de31041202ba36c1f62285

**Comment by rithvikvibhu** [comment]
Added in #334.
