### ISSUE TITLE
hsd v2.3.0

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#284]
hsd v2.3.0rc1 has been tagged and I'm asking developers to test it out before we officially release:

tag: https://github.com/handshake-org/hsd/releases/tag/v2.3.0rc1
PRs merged for this release: https://github.com/handshake-org/hsd/milestone/2?closed=1
changelog: https://github.com/handshake-org/hsd/blob/master/CHANGELOG.md#unreleased

The biggest impact for bob users:
- lookahead is now 200
- all the TRANSFER/FINALIZE balance bugs are fixed 🤞 
- new API endpoint `/deepclean` will wipe out the wallet corruption, and must be followed by a rescan to restore the sane balance of the wallet after getting trashed by name transfers both in and out
  - `deepclean` has an advantage over regular rescans or seed imports in that it does NOT delete the wallets list of public keys, so the lookahead should not affect it, it already knows all its addresses and should be able to find all chain TXs
  - `deepclean` requires a parameter: `I_HAVE_BACKED_UP_MY_WALLET=true` there are a few ways to do this besides just backing up the mnemonic phrase: [backup](https://hsd-dev.org/api-docs/?shell--cli#backupwallet) [dump](https://hsd-dev.org/api-docs/?shell--cli#dumpwallet) or manually copy the datadir after shutdown

I think it'd be helpful to have a `deepclean + rescan` button in Bob that helps the user back up their wallet first just in case. This should be the end of the weird locked balance bugs from name transfers!

**Comment by rithvikvibhu** [comment]
Already on hsd 2.4.0+ now and deepclean was added in #308.
