### ISSUE TITLE
0.6.2 does not run on Ubuntu 20.10

### ISSUE THREAD

**Issue by Thijxx** [kyokan/bob-wallet#291]
I followed the steps in the README and in the end when I run the AppImage it does not start and does not show any error.
Ubuntu 20.10, updated.

## Expected Behavior
Start the app.

## Current Behavior
Nothing. No error.

## Steps to Reproduce
Install Ubuntu 20.10, follow the README

## Context (Environment)
0.6.2 un Ubuntu 20.10

## Logs
No app, no logs.

**Comment by rithvikvibhu** [comment]
Is there a log when running the AppImage from a terminal?
```sh
cd dist
./Bob-0.6.2.AppImage
```

**Comment by Thijxx** [comment]
> Is there a log when running the AppImage from a terminal?
> 
> ```shell
> cd dist
> ./Bob-0.6.2.AppImage
> ```

No, nothing. This is the latest part of my log.

```

jan 17 11:01:04 Thijs systemd[1]: Condition check resulted in Bluetooth service being skipped.
░░ Subject: A start job for unit bluetooth.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit bluetooth.service has finished successfully.
░░ 
░░ The job identifier is 16499.
jan 17 11:01:04 Thijs kernel: bob-wallet[988762]: segfault at 3f800000 ip 00007f4a7cc87870 sp 00007ffcad2cdc90 error 4 in libnode.so.72[7f4a7cb04000+1606000]
jan 17 11:01:04 Thijs kernel: Code: 7d b0 48 89 55 a 0f 84 ed 01 00 00 49 89 f7 48 89 f0 31 d2 0f 1f 40 00 <48> 8b 00 48 83 c2 01 48 39 c1 75 f4 48 8d 45 c0 48 89 55 b8 48 89
jan 17 11:01:04 Thijs systemd[2043]: tmp-.mount_Bob\x2d0.29atjJ.mount: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit UNIT has successfully entered the 'dead' state.
jan 17 11:01:04 Thijs systemd[1]: tmp-.mount_Bob\x2d0.29atjJ.mount: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit tmp-.mount_Bob\x2d0.29atjJ.mount has successfully entered the 'dead' state.
```

**Comment by rithvikvibhu** [comment]
Hm, weird. Btw, by "log", I meant the terminal output but I'm guessing it was blank.

Try running in dev mode?
```sh
npm run dev
```

**Comment by Thijxx** [comment]
> Hm, weird. Btw, by "log", I meant the terminal output but I'm guessing it was blank.
> 
> Try running in dev mode?
> 
> ```shell
> npm run dev
> ```

```
> bob-wallet@0.6.2 dev /home/thijs/repos/bob-wallet
> cross-env START_HOT=1 npm run start-renderer-dev


> bob-wallet@0.6.2 start-renderer-dev /home/thijs/repos/bob-wallet
> cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js

@babel/preset-env: `DEBUG` option

Using targets:
{
  "electron": "6.0.7"
}

Using modules transform: auto

Using plugins:
  syntax-async-generators { "electron":"6.0.7" }
  syntax-object-rest-spread { "electron":"6.0.7" }
  proposal-json-strings { "electron":"6.0.7" }
  syntax-optional-catch-binding { "electron":"6.0.7" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
Starting Main Process...

> bob-wallet@0.6.2 start-main-dev /home/thijs/repos/bob-wallet
> cross-env HOT=1 NODE_ENV=development electron --inspect=5858 -r @babel/register -r @babel/polyfill ./app/main.js

Debugger listening on ws://127.0.0.1:5858/4c68db91-2b4b-4ab8-b0b0-01cd92024eb4
For help, see: https://nodejs.org/en/docs/inspector
@babel/preset-env: `DEBUG` option

Using targets:
{
  "electron": "6.0.7"
}

Using modules transform: auto

Using plugins:
  syntax-async-generators { "electron":"6.0.7" }
  syntax-object-rest-spread { "electron":"6.0.7" }
  proposal-json-strings { "electron":"6.0.7" }
  syntax-optional-catch-binding { "electron":"6.0.7" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
@babel/preset-env: `DEBUG` option

Using targets:
{
  "electron": "6.0.7"
}

Using modules transform: auto

Using plugins:
  syntax-async-generators { "electron":"6.0.7" }
  syntax-object-rest-spread { "electron":"6.0.7" }
  proposal-json-strings { "electron":"6.0.7" }
  syntax-optional-catch-binding { "electron":"6.0.7" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.


```

**Comment by rithvikvibhu** [comment]
Nothing wrong here. It just takes a while to start (~30s for me, maybe wait for 1m). After this, 2 windows should show up: one chrome devtools and the other a Bob Wallet window.

**Comment by Thijxx** [comment]
> Nothing wrong here. It just takes a while to start (~30s for me, maybe wait for 1m). After this, 2 windows should show up: one chrome devtools and the other a Bob Wallet window.

It returns to the command prompt and then nothing happens, waited 10 minutes. Maybe I'm missing dependencies of some kind?  Do I need to have chrome installed since you mentioned the devtools?

**Comment by rithvikvibhu** [comment]
>Maybe I'm missing dependencies of some kind? Do I need to have chrome installed since you mentioned the devtools?

Nope, I don't think so (but I do have chrome installed).

On closer look, the first log has
```
 bob-wallet[988762]: segfault at 3f800000 ip 00007f4a7cc87870 sp 00007ffcad2cdc90 error 4 in libnode.so.72[7f4a7cb04000+1606000]
```
Not sure what's causing the segfault. Also can't find any old issues similar to this. Hopefully someone else knows what's wrong.

**Comment by Thijxx** [comment]
Update regarding 0.7.0, this also does not run on Ubuntu.
The error message I get is: `qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 619, resource id: 16777391, major code: 40 (TranslateCoords), minor code: 0`

**Comment by rithvikvibhu** [comment]
@Thijxx is this still a problem with v0.9.0?

**Comment by Thijxx** [comment]
@rithvikvibhu the current version runs great!
