### ISSUE TITLE
Atomic swap feature not showing received funds as a transaction

### ISSUE THREAD

**Issue by peepohns** [kyokan/bob-wallet#292]
I just did an atomic swap as a seller and although I did receive the HNS (my wallet balance updated) I do not see it as a separate received transaction in the wallet. I only see the "Finalized" transaction. I checked with another seller that used the feature and the same happened to him.
![Capture](https://user-images.githubusercontent.com/77860971/105551188-8031b580-5ca6-11eb-8a92-266c1bc49a6d.PNG)

**Comment by pinheadmz** [comment]
This is good feedback. The atomic swap transaction is a non-standard construction that does two things in one TX: It's a FINALIZE and a payment.

The Bob UI is designed to only show one "thing" per transaction, so it fits nicely on one line. If you used the API to send a TX with two outputs and pay two people at once for example, I'm pretty sure the UI would just display the first payment. Notice that this UI function also hides the change output from the user etc, so it's just a nice simplification.

It's not super easy for Bob to "guess" what single label to use for each TX. The logic is [here](https://github.com/kyokan/bob-wallet/blob/860624647944a15741ee27f6dd375738e7cbda99/app/ducks/walletActions.js#L329) and could probably be improved.

**Comment by peepohns** [comment]
Gotcha! I saw your atomic swap video and the transaction showed so I thought it was a bug of some sort. Appreciate the clarification!
![dd](https://user-images.githubusercontent.com/77860971/105611925-9437ee80-5d5c-11eb-812f-22c0a5552d9a.PNG)

**Comment by pinheadmz** [comment]
Ohhhhh good catch! Yeah I am running a slightly different / older version of Bob here too.

**Comment by peepohns** [comment]
Yup! I think it can be confusing for some new users if they don't see the deposit transaction separately (especially if they transact a lot). I wasn't sure at first if I got it as it was a small amount but checked by peaking at the txid.
