### ISSUE TITLE
Modified hsd used by Bob

### ISSUE THREAD

**Issue by rithvikvibhu** [kyokan/bob-wallet#295]
Not a bug, but curious why Bob uses a modified hsd [in package.json](https://github.com/kyokan/bob-wallet/blob/master/package.json#L150).

Is this really needed, and if yes, can these changes be added upstream to hsd so it's easier to test and update?

**Comment by pinheadmz** [comment]
I think part of the reason Bob diverged from hsd is honestly - there were several months last year with out any maintenence or progress on hsd at all. The Bob developers needed to fix the persistant rescan bug and just forked hsd for that. I'm currently working on a robust wallet overhaul for the rescan bug and hope to have an open PR for hsd within a week or two.

**Comment by rithvikvibhu** [comment]
Oh sweet! Looking forward to that :)
