### ISSUE TITLE
Something wrong :/

### ISSUE THREAD

**Issue by panpansh** [kyokan/bob-wallet#299]
Hi, i'm using bob wallet and I think I have a problem take a look please :

this morning, placed 3 bids but 2 seems not to be ok : 

<img width="994" alt="Capture d’écran 2021-01-31 à 16 06 12" src="https://user-images.githubusercontent.com/790586/106388347-5b43ed80-63de-11eb-814b-a27bfe47282b.png">
<img width="963" alt="Capture d’écran 2021-01-31 à 16 07 22" src="https://user-images.githubusercontent.com/790586/106388360-6bf46380-63de-11eb-8651-419334e421ae.png">

after that, trying to check my wallet :

<img width="656" alt="Capture d’écran 2021-01-31 à 16 04 53" src="https://user-images.githubusercontent.com/790586/106388286-15872500-63de-11eb-8aa9-e59baf02d6e4.png">

https://hnscan.com/address/hs1qta7wgwc6ryk9pys7nddvmsxxu4q5dtwjqcquuh

<img width="786" alt="Capture d’écran 2021-01-31 à 16 05 34" src="https://user-images.githubusercontent.com/790586/106388313-2cc61280-63de-11eb-9c46-5dd394bc80f2.png">

4 hours later, bids ended, transaction is pending and my wallet display 0 on block explorer.

**Comment by sdtsui** [comment]
From what I can see:
- the receive address is supposed to display 0 and does not represent your whole wallet, it will only get funds if funds are sent to it
- it looks like your bids weren't accepted by the chain - you can zap (in settings) and re-send them

I am closing this as it doesn't have a specific question that I can see.

Feel free to re-open if you're still having issues.
