### ISSUE TITLE
Auction rescan broken when using custom RPC, (0.6.2)

### ISSUE THREAD

**Issue by williamjohnstone** [kyokan/bob-wallet#310]
## Expected Behavior
Auction rescan should work when using custom RPC 

## Current Behavior
When using custom RPC even after rescanning an ongoing auction no bids are displayed in Bob.

## Steps to Reproduce
1. Connect to a custom RPC node
2. Rescan any ongoing auction with bids 
3. See that no bids are displayed.

## Context (Environment)
Trying to use an external node with Bob instead of the internal one.

## Logs
N/A

## Screencap
![image](https://user-images.githubusercontent.com/37273113/109584558-ae05e780-7af9-11eb-8497-b925819cb8dc.png)

![image](https://user-images.githubusercontent.com/37273113/109584571-b2320500-7af9-11eb-9b83-b8b87c56dd42.png)

## Additional Info
In a discussion on telegram, @pinheadmz said `the "rescan auction" function calls wdb.rescan() which may have new functionality in bob, i dunno I think depending on your version the local rescan method has been stubbed in` and @chikeichan said this was likely the problem.

**Comment by rithvikvibhu** [comment]
When connected with RPC, even own bids don't show up.
