### ISSUE TITLE
Inaccurate domain expiry time [v0.7.0-rc.2]

### ISSUE THREAD

**Issue by nlydv** [kyokan/bob-wallet#318]
I was looking at my recently transferred in domain name and it said there's 2 years (-1 day) left until expiration, yet in the domain overview it says that there is only "~a year" until expiration.

However, another name I have expires a couple months sooner but still accurately says "~2 years" until expiry.

Guessing the bug has to do with it being recently transferred (and expiration clock reset).
<img width="1136" alt="Screen Shot 2021-03-27 at 5 59 45 PM" src="https://user-images.githubusercontent.com/39429628/112737328-bd752680-8f27-11eb-9863-a1b52ac2600d.png">
<img width="1136" alt="Screen Shot 2021-03-27 at 5 59 49 PM" src="https://user-images.githubusercontent.com/39429628/112737329-be0dbd00-8f27-11eb-9f2e-03883ba8d560.png">

**Comment by pinheadmz** [comment]
Good catch. Most auction timing is based on the `ns.height` property but expiration is based on a different property `ns.renewal` which as you correctly assume gets updated when you transfer a name (meaning the recipient gets a fresh 2 years). My guess is the code uses `ns.height` for everything which isn't totally right.
