### ISSUE TITLE
[Feature] Deeplink proxy thru bobwallet.io

### ISSUE THREAD

**Issue by Falci** [kyokan/bob-wallet#320]
## What?
Instead of using deeplinks directly, like `bob://updatename?...` we could have a redirect page on `https://bobwallet.io`.

## Why?
Bob's deeplink won't do anything if the user don't have Bob wallet installed yet.
The page on BobWallet.io should show instructions like "If you don't have bob yet, download it here. Trying to redirect..."

## How?
Here's an example from Telegram: https://t.me/bobwallet. This is just a regular link. But that page has a deeplink with Telegram's native app.

**Comment by pinheadmz** [comment]
I'm not sure bouncing cryptocurrency wallet links off of a website is a good idea. [When Jacky first added deeplinks I asked about using a more regular standard like BIP-21](https://github.com/kyokan/bob-wallet/pull/274#issuecomment-731738694) but he said the deep links were just for internal navigation inside Bob (so you'd have Bob installed anyway)

**Comment by rithvikvibhu** [comment]
One solution could be to do what Microsoft Teams and other apps do.

Sinpapeles opens with `bob://` link in the background, and displays a modal "Don't have Bob? Install it now" or whatever. It should also be possible to only show the modal if the mouse pointer remains in the window (i.e. Bob didn't open).

**Comment by Falci** [comment]
> (so you'd have Bob installed anyway)

Yes, if I'm creating a link to Bob, I expect if to be there. But what happens when it's not installed yet?

**Comment by rithvikvibhu** [comment]
>I'm not sure bouncing cryptocurrency wallet links off of a website is a good idea

Agreed, even sinpapeles wouldn't want to open a 3rd party website just to deeplink.

@Falci does https://github.com/kyokan/bob-wallet/issues/320#issuecomment-814208749 work?

**Comment by rithvikvibhu** [comment]
Closing this now, feel free to reopen to discuss more.
