### ISSUE TITLE
List of active Auctions

### ISSUE THREAD

**Issue by befranz** [kyokan/bob-wallet#325]
If you have a lot of names in Bob it's hard or impossible to follow the status of names/auctions. It would be cool to have a tab where you can filter names on current state (at least BIDDING) with sort option (last open as default).

**Comment by rithvikvibhu** [comment]
Bids are grouped by auction status now (since v0.8.0 I think) and takes care of this I think?

**Comment by rithvikvibhu** [comment]
Closing this now as Your Bids shows bids grouped and it's possible to see active auction bids. Feel free to reopen to discuss if not.
