### ISSUE TITLE
"Bid Unrevealable, unable to Repair"

### ISSUE THREAD

**Issue by godelbrot** [kyokan/bob-wallet#328]
I have a pair of bids right now that used mask amounts and have now transitioned to the reveal phase. I am being given a warning that if I don't reveal these bids by the end of the reveal period I will lose the bid and the amount, but I am unable to reveal them, and the button that supposedly should be used to fix this, "Repair Hidden Bids" is greyed out and I can't click it. Large bids, important names and the clock is ticking. What are my options here? 

*edit*

so I just was explained that I need to manually type in what my hidden bid amount was in the field, but I can't recall the exact number so I am just having the brute force it, is there anywhere within the gui that saves what the hidden bid amount was?

**Comment by pinheadmz** [comment]
Did you import this wallet from a seed phrase? Normally you won't need to repair bids unless your wallet was created from a rescan. The bid values are normally saved in hsd (the full node inside bob) but if you import a wallet from seed phrase of course that data is gone, and the whole point of blind bids is that those values are secret, so the human must remember them if the computer does not. We have some ideas for how to encrypt the bid values and leave them on chain for recovery, but nothing fleshed out yet.

**Comment by rithvikvibhu** [comment]
@godelbrot read your edit. Looks like you were able to enter the bid values in the input field and brute force it. Did that work?

**Comment by rithvikvibhu** [comment]
Closing this now, but feel free to reopen if this is still an issue (from the edit, looks like it's resolved though).
