### ISSUE TITLE
Bob showed a negative "spending balance"

### ISSUE THREAD

**Issue by Omar-Itani** [kyokan/bob-wallet#332]
After placing a bunch of bids on different names, I noticed my wallet showed a negative balance...although my balance is once again positive after I used the "reveal all" function.

Mac OS, version 0.7.0

**Comment by rithvikvibhu** [comment]
I'm trying to think of a situation where this could happen. Bids reduce balance, Reveals increase balance.

I was thinking it could be a state between confirmed and unconfirmed balances, but only `spendableBalance` considers pending txs:

https://github.com/kyokan/bob-wallet/blob/6f3f93bf202740f27cda1b46684d78e94ae68a96/app/ducks/walletReducer.js#L81

But `spendableBalance` is never used with other calculated values (that use `getBids`, `getReveals`, `getNames`). There's no subtraction I can see.

@Omar-Itani do you have an example or a list of steps/bids that results in a negative balance?

**Comment by Omar-Itani** [comment]
no sorry I don't this was almost 1 year ago :)
