### ISSUE TITLE
building for Linux arm64

### ISSUE THREAD

**Issue by chaserene** [kyokan/bob-wallet#340]
in case it's possible, can you please include instructions in the README.md?

and if it's not, I'd like to ask for this as a feature request.

**Comment by rithvikvibhu** [comment]
Hey @chaserene. 

I haven't tested, but this _should_ build for arm64:

```
npm install       # install dep
npm run build     # generate files to be packaged

# package for arm64
electron-builder build --arm64 --publish never
```

Let me know if it works (or doesn't)!

**Comment by rithvikvibhu** [comment]
Closing now, but I'm still curious if the arm64 build worked! Feel free to reopen if it didn't.
