### ISSUE TITLE
Reveal Length Displayed Incorrectly

### ISSUE THREAD

**Issue by codemaster138** [kyokan/bob-wallet#341]
I'm looking at some auctions in bob, but I just can't help but notice that even though the **10-day** reveal period is almost over, bob says that the reveal period is 2767 days long... Seems to be happening on all auctions, although I can't confirm whether it only happens on auctions where I bid.

## Expected Behavior
Bob displays an approximately correct time estimate for when the reveal period should end.

## Current Behavior
As described above, bob displays somewhere between 2700 and 2900 days left for the auction.

## Steps to Reproduce
1. View an auction that is currently in the reveal period
2. See issue

## Context (Environment)
- Operating System: macOS 11.2.3 (Big Sur)
- Device: 13" **M1** MacBook Pro
- Bob Version: 0.7.0

## Logs
[bob-debug-main.log](https://github.com/kyokan/bob-wallet/files/6425281/bob-debug-main.log)

## Screencap
<img width="1364" alt="Screenshot 2021-05-05 at 07 59 10" src="https://user-images.githubusercontent.com/43313420/117102691-277bb980-ad79-11eb-8009-f6b1a1ac7d93.png">

**Comment by rithvikvibhu** [comment]
This is fixed in v0.7.1 (get from [releases](https://github.com/kyokan/bob-wallet/releases)). Try updating Bob.

**Comment by codemaster138** [comment]
Oh, ok. I'll do that

**Comment by codemaster138** [comment]
Yeah, that fixes it, thanks!
