### ISSUE TITLE
Ledger: xpub check before each signing request

### ISSUE THREAD

**Issue by rithvikvibhu** [kyokan/bob-wallet#352]
For https://github.com/kyokan/bob-wallet/pull/344#issuecomment-838400387.

Need to ensure that the correct Ledger device associated with the logged in wallet is connected.

**Comment by pinheadmz** [comment]
Closed by https://github.com/kyokan/bob-wallet/pull/344/commits/fb9ce083e748b642c2024fef7a28bd73fc1613ff

**Comment by rithvikvibhu** [comment]
Added in #344.
