### ISSUE TITLE
A formal developer guide would be nice

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#353]
I think this link: https://github.com/kyokan/bob-wallet#building-from-source to my old gist may be outdated. Now that USB dependencies are required for building and we're trying to solicit more contributors, either the README could be improved or a new CONTIRBUTING.mc file could be added.

**Comment by rithvikvibhu** [comment]
Was almost done with https://github.com/kyokan/bob-wallet/wiki/Developer-Guide until I realized you were talking about build instructions specifically 😐. Anway, #444 updates the readme and it seems pretty clear now right?

**Comment by pinheadmz** [comment]
That dev guide is awesome! 🕺  Closing.
