### ISSUE TITLE
Importing the second name makes data for the first name disappear

### ISSUE THREAD

**Issue by befranz** [kyokan/bob-wallet#354]
There‘s obviously a Ui issue which @pinheadmz described here:
https://github.com/handshake-org/hsd/issues/595

**Comment by pinheadmz** [comment]
To continue the report from the hsd issue...


Where I'm tracking it now is in (wallet) `rpc getauctioninfo`, where I see a difference between hsd and bob wallet's hsd rpc:

`hsw-rpc getauctioninfo btcproduction` and `hsw-rpc getauctioninfo btcpractice` BOTH return json with `bids` arrays in hsd, but in Bob only the most recent name returns, the other throws `"Auction not found"`

**Comment by pinheadmz** [comment]
Ok my suspicion now is this behavior is due to the remote `WalletNode` -- If I can confirm this, I'm going to open this issue back up in hsd.

**Comment by pinheadmz** [comment]
Yeah I'm really blown away by this... exact same commands between hsd and Bob, both configured with remote wallet node, and the second importname blows away the first on bob wallet only. Not even using the UI but CLI commands:

`gen` = bash alias for generatetoaddress

using primary wallet, open two name auctions and place one bid on each:

```
  export HSD_NETWORK=regtest
  gen 200
  hsw-rpc sendopen one1
  hsw-rpc sendopen two2
  gen 6
  hsw-rpc sendbid one1 1 1
  hsw-rpc sendbid two2 2 2
  gen 1
  hsw-rpc getauctioninfo one1
  hsw-rpc getauctioninfo two2
```

create second wallet and attempt to import both names:
```
  hsw-cli mkwallet w2
  hsw-rpc selectwallet w2
  hsw-rpc getauctioninfo one1        # []
  hsw-rpc getauctioninfo two2        # []
  hsw-rpc importname one1 200
  hsw-rpc getauctioninfo one1        # [ has info ]
  hsw-rpc getauctioninfo two2        # []
  hsw-rpc importname two2 200
  hsw-rpc getauctioninfo two2        # [ has info ]
  hsw-rpc getauctioninfo one1        # []
```

**Comment by pinheadmz** [comment]
OK, this is an hsd issue after all, this issue can be closed... https://github.com/handshake-org/hsd/issues/595#issuecomment-847294518
