### ISSUE TITLE
Repair Unknown bids

### ISSUE THREAD

**Issue by krunkosaurus** [kyokan/bob-wallet#379]
When checking on the status of a domain I bidded on I see "Repair Unknown Bids". This button is not clickable. (see screenshot). I think this happened because I bidded on the auction using Bobwallet on another computer and checked the status the next day on this one. Both have Bob Wallet using the same private key.

The issue may have also been caused by clicking "Reveal all" under the domains section, previously.

## Expected Behavior
To see the status of the domain.

## Current Behavior
See a button that says "Repair Unknown Bids"

## Context (Environment)
Macbook Pro Big Sure 11.04

## Screencap
<img width="1056" alt="Screen Shot 2021-07-04 at 2 28 01 AM" src="https://user-images.githubusercontent.com/20738/124363795-f849d180-dc6f-11eb-98c8-f7287380c4a6.png">

**Comment by pinheadmz** [comment]
Click on the table on left side where it says "unknown bid" and it will let you type in your secret bid value there.

**Comment by krunkosaurus** [comment]
Thanks for your quick reply. I don't have access to the other computer currently. Shouldn't bob wallet be able to know the bid since it has my private key and the blockchain downloaded? I am unable to reveal my bid because it's stuck on this step.

**Comment by rithvikvibhu** [comment]
The true bid value isn't public until the bid is revealed, they are stored locally only. So one Bob instance won't know the exact bid value if the bid was placed from another Bob.

**Comment by krunkosaurus** [comment]
I was told in TG chat that this is a feature being added to Handhsake itself (encrypting bid+blind on the actual blockchain) so closing this ticket in the meantime.
