### ISSUE TITLE
Shakedex.fulfillSwap IPC log is not sanitized (wallet password visible)

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#388]
Just testing on regtest so my wallet password is the ever-secure always-memorable `123456789`.

I also wonder if Shakedex data should have a network string set in the payload as well and API request as well, it would be super cool for testing if there was a simnet. 

```
Executing IPC method. {
  jsonrpc: '2.0',
  method: 'Shakedex.fulfillSwap',
  params: [
    {
      id: 766,
      name: 'faggot',
      publicKey: '02b3c0355788242bc48c4924d749879271c751d37b1d821e0dfb2dfdf4c3af5c28',
      paymentAddr: 'hs1q4all8ftdtwc49djux36tku425ex9ga6h85xpp4',
      lockingTxHash: 'ee74726d5190e20c692e9b2653ea62d6bf03e6cf9f08e9160fe19971ebee552e',
      lockingOutputIdx: 0,
      spendingTxHash: null,
      spendingStatus: null,
      createdAt: 1626822897473,
      updatedAt: 1626822897473,
      bids: [Array]
    },
    {
      price: 45000000000,
      signature: '09116995dce7ddbfcdb44d67ccf3b38b0e360342506340d090385b9bc0c11bfa4deae2982beccdd0eaa719f19bf3615e9f001f594c57c486170d9ff07929d96a84',
      lockTime: 1626995691000
    },
    '123456789'
  ],
  id: 432
}
```

**Comment by rithvikvibhu** [comment]
#460 for sanitizing passphrase.

>I also wonder if Shakedex data should have a network string set in the payload as well and API request as well, it would be super cool for testing if there was a simnet.

wdym?

**Comment by pinheadmz** [comment]
shoot sorry for the duplciate, i have bad memory I guess. lets close this and continue in #460. The comment about networks really belogns in shakedex repo - the SD protocol needs a network identifier so bob in regtest doesnt try to fill mainnet swaps...
