### ISSUE TITLE
Highest Lockup NaN HNS error when bidding ends

### ISSUE THREAD

**Issue by NetOpWibby** [kyokan/bob-wallet#396]
## Expected Behavior

I should see the highest lockup in number form.

## Current Behavior

`NaN` shouldn't be displayed.

## Steps to Reproduce

Not sure if the decimal has something to do with this error.

## Screencap

<img width="1136" alt="SS 2021-07-26 at 11 22 08 AM" src="https://user-images.githubusercontent.com/1288356/127039092-e3ab0d4d-9a01-434e-806e-4d9e9f740542.png">

**Comment by rithvikvibhu** [comment]
I think this was fixed 1-2 releases ago. Is this the latest Bob (0.8.0)?

**Comment by NetOperatorWibby** [comment]
Yup!

**Comment by rithvikvibhu** [comment]
Okay got the same issue on all REVEALing names with my bids that have won (not sure if this is the case for lost auctions too).

**Highest Lockup** is calculated with:
```js
const highest = Math.max(bids.map(bid => bid.value));
```
so at least 1 `bid.value` isn't right.

Haven't tried reproducing in regtest, but the bids are:
![image](https://user-images.githubusercontent.com/5113343/128017583-50466aa8-ec92-4df0-aa84-13dcae6ec1aa.png)

- All bids revealed (I revealed both first)
- Half way through REVEAL currently
