### ISSUE TITLE
Remove or raise atomic swap limit

### ISSUE THREAD

**Issue by peepohns** [kyokan/bob-wallet#399]
The atomic swap feature is [capped at 2000 $HNS ](https://github.com/kyokan/bob-wallet/blob/9ac7b6da645509ff5ef78c9c3d3deea6ccbf10cd/app/background/wallet/service.js#L636-L638). 

I wanted to know if this can be raised or even removed. It's such an awesome feature and one I could see being very very popular especially among sellers switching to a more decentralized marketplace.

**Comment by rithvikvibhu** [comment]
Resolved in #441
