### ISSUE TITLE
Custom RPC not working (Bob 0.8.0 Stable)

### ISSUE THREAD

**Issue by magicstone1412** [kyokan/bob-wallet#407]
I have an orange prime running full node of HSD. I have tried to use it as RPC node but was not successful. Rescan function is running forever.

## Expected Behavior

Bob will work normally when using custom RPC function

## Current Behavior
![infinity](https://user-images.githubusercontent.com/9553811/131338580-cabd6079-9134-4b89-b7ac-1a878447ca12.jpg)

## Steps to Reproduce

RPC settings

![RPC-settings](https://user-images.githubusercontent.com/9553811/131338868-4fbfa86c-65c1-40c2-9767-d121484db996.jpg)

Check connection

![kiem-tra-ket-noi-voi-rpc](https://user-images.githubusercontent.com/9553811/131338930-a3314830-fc88-4c84-8963-8f08966a193e.jpg)

**Comment by pinheadmz** [comment]
If you are able to run in dev mode, can you review / test this PR: https://github.com/kyokan/bob-wallet/pull/397

**Comment by rithvikvibhu** [comment]
@magicstone1412 did that PR or the latest version of Bob fix this issue?

**Comment by rithvikvibhu** [comment]
#397 was merged and released in v0.9.0 and RPC seems to be working for others who had the same issue. Closing this now, feel free to reopen if it still doesn't work in the latest version.
