### ISSUE TITLE
Remote RPC node connection over HTTPS is disabled

### ISSUE THREAD

**Issue by nlydv** [kyokan/bob-wallet#411]
### It doesn't seem possible to configure a remote RPC connection to a TLS secured node.
The remote config modal's "protocol" dropdown only gives one option: `HTTP`

<img width="1136" alt="Screen Shot 2021-09-16 at 12 55 37 PM" src="https://user-images.githubusercontent.com/39429628/133662878-d253ad03-ecc3-4236-8ce5-312c05dc5857.png">

After looking around to see if there was a simple switch to fix this, I found that the option was commented out here: https://github.com/kyokan/bob-wallet/blob/1c6743e1ea8fdffe5607b8cbb6a9eef6a63ab7f7/app/pages/Settings/CustomRPCConfigModal.js#L209

Unfortunately, simply uncommenting the line, re-building the app, and selecting the new `HTTPS` dropdown option proved unusable (I'm sure that's why it was commented out to begin with). Bob did at least successfully authenticate with the remote node though, at least for a couple seconds, before reverting to the `No connection` state. Manually going back to the RPC modal to save the settings made it reconnect but again only for a couple seconds.

Ruled out misconfiguration on my end since I was able to easily connect to the node with HTTPS using a standalone `hsw` instance via command line.

Not sure what background code might be tripping up HTTPS connections, but I've reverted my node to unsecured HTTP for now.

**Comment by pinheadmz** [comment]
> Not sure what background code might be tripping up HTTPS connections, but I've reverted my node to unsecured HTTP for now.

Do not do this! If I can guess the IP address of your node I can sniff the API key and to terrible things like invalidate valid blocks and trigger reorgs and rescans and shut you down completely.

Insecure remote RPC connections MUST be configured behind a firewall or locally.

p.s. when you rebuilt Bob with the line un-commented, that was also on top of the recent merge #397 ?

**Comment by nlydv** [comment]
> Insecure remote RPC connections MUST be configured behind a firewall or locally.

Well I do have it behind a proxy to only allow connections from whitelisted IPs, so not totally naked.

> p.s. when you rebuilt Bob with the line un-commented, that was also on top of the recent merge #397 ?

Not on top of the _merged_ version, no.
Built it off of your original fork branch `pinheadmz:walletplugin` rather than the post-merge `kyokan:master` branch.

**Comment by pinheadmz** [comment]
> Well I do have it behind a proxy to only allow connections from whitelisted IPs, so not totally naked.

Still you API key is being exposed to the open internet and whatever wallet data you are sending (not private keys, this would just be more a privacy issue)

>  Built it off of your original fork branch pinheadmz:walletplugin rather than the post-merge kyokan:master branch.
Ok thanks Ill try it out myself next week.
