### ISSUE TITLE
chain database version mismatch

### ISSUE THREAD

**Issue by chaserene** [kyokan/bob-wallet#415]
I tried to run Bob Wallet 0.8.0 with the hsd datadir I use with hsd 2.4.0.

## Expected Behavior
the wallet recognizes the data.

## Current Behavior
the wallet shows the following error:
"Database version mismatch for database: "chain". Please run a data migration before opening."
the error message isn't too helpful in how you can do the migration it asks for.

## Steps to Reproduce
1. have a synced hsd
2. set Bob Wallet's hsd datadir to your hsd's datadir
3. start Bob Wallet

## Logs
I would show if I knew where Bob Wallet keeps them

**Comment by pinheadmz** [comment]
Also note, this isn't really a recommended configuration. Bob Wallet has a remote rpc mode you can use to connect to your hsd full node via http.

**Comment by rithvikvibhu** [comment]
As long as the external hsd version and Bob's hsd match, there shouldn't be any issues. Feel free to reopen if it still doesn't work.
