### ISSUE TITLE
Recovery phrase can be pasted 

### ISSUE THREAD

**Issue by hasparus** [kyokan/bob-wallet#420]
Howdy 👋

The recovery phrase during wallet creation can be pasted, but the text on screen says it can't be.

## Expected Behavior

Bob tells me pasting the recovery phrase is disabled to ensure I backed it up on paper.
I'm not quite sure that I expect that behaviour, but it's described in the UI, and I'd expect the text to be correct :)

## Current Behavior

I pasted my recovery phrase 👿.

## Steps to Reproduce

1. Create new wallet, name it.
2. Copy recovery phrase.
3. Paste recovery phrase.

## Context (Environment)

Creating a new wallet on Windows.

## Logs

[bob-debug-main.log](https://github.com/kyokan/bob-wallet/files/7402587/bob-debug-main.log)

## Screencap

![image](https://user-images.githubusercontent.com/15332326/138550472-3c9ceda0-88b9-4d34-886d-65cb75b57a45.png)

**Comment by rithvikvibhu** [comment]
**Copying**
How about a warning/confirmation if someone tries to copy?
If they accept, then copy to clipboard, if not, don't.

**Pasting**
I think allowing paste is fine?
Even if pasting is disabled, users will still have the copied text from when they try to paste - we can't stop this

**Comment by rithvikvibhu** [comment]
Hey @hasparus @pinheadmz. #476 addresses this by adding a confirm on copy and warning on paste. Can you try it out / leave a review?
If you don't want to clone and run in dev mode, there's binaries for Windows and Linux here: https://github.com/rithvikvibhu/bob-wallet/actions/runs/1899817141
