### ISSUE TITLE
Fee rate suggestions are misleading

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#426]
https://github.com/kyokan/bob-wallet/blob/ecb89de4a644d0c0c3e975df58d3048bb3159d9f/app/components/SendModal/index.js#L26-L30

It's really misleading to suggest to users that a TX will get confirmed in less than 5 minutes.

Especially since the block targets used in estimations are:

https://github.com/kyokan/bob-wallet/blob/ecb89de4a644d0c0c3e975df58d3048bb3159d9f/app/background/node/service.js#L450-L452

...if anything this would imply target confirmation times of 10 minutes, 20 minutes, and 50 minutes.

----

Truth is, network fees are irrelevant right now and the fee estimator doesn't even have enough data (tx volume) to provide actual estimates on top of the hard coded minimum fee:

```
$ hsd-rpc estimatesmartfee 1
{
  "fee": 0.100091,
  "blocks": 1
}
$ hsd-rpc estimatesmartfee 2
{
  "fee": 0.100091,
  "blocks": 2
}
$ hsd-rpc estimatesmartfee 5
{
  "fee": 0.100091,
  "blocks": 5
}
```

----

I'm not sure what the best UI is for this but certainly the "5 minutes" needs to be removed or changed.

**Comment by rithvikvibhu** [comment]
This message was set to a constant of 15 mins regardless of fee rate when addding i18n (#443):
https://github.com/kyokan/bob-wallet/pull/443/files#diff-cb115d29f77311695f87caf78f5dcc55431f8c2daee49e9e7ec088a247fea981R414

Think this resolves the issue as the estimates are not shown anywhere.
