### ISSUE TITLE
Issue with BOB desktop 9.0 Release Candidate

### ISSUE THREAD

**Issue by DIPMR** [kyokan/bob-wallet#429]
There are 2 bids to be revealed and it's showing in the "PORTFOLIO" tab, the card, but the reveal bids are not showing in the "BIDS" tab. Even it s not showing the numbers for "bidding()" nor for closed  too. Its showing " but not the breakdown of all bids. ALL" I can reveal the bids from the card though.
It's SPV enabled.
Please find attached screenshots.
![1bb](https://user-images.githubusercontent.com/35240043/141693027-601a9ffa-f64f-4739-b04c-83f40595ea8d.JPG)
![2b](https://user-images.githubusercontent.com/35240043/141693181-777feaf7-f0a4-40d7-a6f4-a62018821c15.JPG)

**Comment by rithvikvibhu** [comment]
Is this with SPV enabled?

**Comment by DIPMR** [comment]
Yes

**Comment by DIPMR** [comment]
And everytime I close it, all the names from "watching" tab disappears.
