### ISSUE TITLE
wdb unresponsive after switching between rpc and local node

### ISSUE THREAD

**Issue by chikeichan** [kyokan/bob-wallet#434]
Reported by @Falci and @rithvikvibhu 

- Create wallet test1
- Switch from local node to remote RPC
(works fine)
- Restart Bob
- Wallet list isn't shown (create, import, ledger wallet box is shown)
- Try to create wallet with same name, errors with "WDB: Wallet already exists."
Current status: Synchronized to RPC

**Comment by rithvikvibhu** [comment]
Looks like #435 fixed it, cannot reproduce anymore. @Falci can you confirm (latest master)? Can re-open if it's not.
