### ISSUE TITLE
GPG Signature to Verify Download

### ISSUE THREAD

**Issue by BTCAlchemist** [kyokan/bob-wallet#436]
Hello, I would like to verify the download with a verified GPG signature since the checksum hash could be manipulated. I may have missed this information. Is the latest release (0.8.0 Stable) signed with GPG by any of the lead devs (and what is their GPG fingerprint or signature)? Thank you in advance.

**Comment by rithvikvibhu** [comment]
Will start signing from the next release with (at least) 1 key :)

For now, v0.9.0:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

49d5273d1fccf29f4bbc63f0a3acd059366d4cebe75f5d8573381ebbfff831e885c9f07fa56adadca416fffd703f84291b7d8c2b78b9b86945ee8b3478799c3f  Bob-0.9.0.AppImage
e57fb88c0b0d930e2fbef29fdf27c1765ce2d6ca83b2fcb9af4963d853056cf34ac813292754cc4482259005c23295990048a32a4f440049f2bd9a73ea20d286  Bob-0.9.0.dmg
028e41169cf7987f57aa0207c2487bcb3bea7129a4264bea76535945a1ee9ca53f3f906f61bd0420a4b3b8afdb4a4fdf8e0bd6fbd426103073ad84966ff6f994  Bob.0.9.0.msi
-----BEGIN PGP SIGNATURE-----

iQEzBAEBCAAdFiEES9ppUueR+VbP+LbSkN+sghCpF9kFAmH/hh4ACgkQkN+sghCp
F9l7tQgAqCVS5m9kTdlac1+Dvksd5BEIwl3510ip6bxunx0eN8gMcrAbr/2difYF
pLqr2FoAFwotx1qX/4UBnVb99tRN64nLgsbPJ3nGT5syAQZtKhP2ajuV4KREu4y1
62hc0ZryrM095niGN2o9LdpVS/cTWK17gIvD+fmV77sNwE6ns2i75QqIg8vOgrAQ
v8mlOYpYXwFahdcp+4c7oArC/Kj+vU3qO+7xI3hNG1e+qX7bdAa8AxbVvK4IVaM3
HD70ZSntnS6ydkl9joQHXPgN+AKdZlWMF1Ac1t5Jw7pt42ybLWroGJ4Jt0Vaiiva
VBiaR9WFwqm38TT4XYxko7mb6OQvUA==
=6oNn
-----END PGP SIGNATURE-----
```

[Verify on Keybase](https://keybase.io/verify)

**Comment by pinheadmz** [comment]
I'm getting a key expired error in GPG for 

 4BDA 6952 E791 F956 CFF8  B6D2 90DF AC82 10A9 17D9 

which is a subkey of 0393 D763 6C08 EFA8 A781  F9CD E851 01DF 1682 E27F

did you push to keyservers besides keybase? i may just need to update from a different server

**Comment by rithvikvibhu** [comment]
Huh, looks like I hadn't published after renewing a subkey. It's on:
- https://blek.ga/key.asc
- https://keyserver.ubuntu.com/pks/lookup?search=0x0393D7636C08EFA8A781F9CDE85101DF1682E27F&fingerprint=on&op=index

and probably other keyservers once they sync up.

**Comment by pinheadmz** [comment]
Verified! thank you :-)
Key Expires: August 20, 2022 at 12:05 PM
We'll revisit this summer!
