### ISSUE TITLE
Multilanguage option

### ISSUE THREAD

**Issue by faltrum** [kyokan/bob-wallet#437]
Could be possible add multilanguage menu in bob Wallet?. I can translate it to Spanish and Catalan language.

**Comment by chikeichan** [comment]
resolved by #440

**Comment by chikeichan** [comment]
@faltrum please see [LOCALE.md](https://github.com/kyokan/bob-wallet/blob/master/LOCALE.md) for i18n instruction - Thanks for your i18n support!!
