### ISSUE TITLE
Doesn't build on Linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by Noxturnix** [kyokan/bob-wallet#445]
I followed the [instruction](https://github.com/kyokan/bob-wallet/tree/v0.9.0#linux) on [v0.9.0](https://github.com/kyokan/bob-wallet/tree/v0.9.0) branch and when I do `npm install` i got this error

```
npm ERR! Package libusb-1.0 was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `libusb-1.0.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! No package 'libusb-1.0' found
```

it seems `libusb-dev` is version 2 instead of 1

```
$ sudo apt list libusb-dev 
Listing... Done
libusb-dev/focal,now 2:0.1.12-32 amd64 [installed]
```

so i installed `libusb-1.0-0-dev` and run `npm install` again. This time i got an another [error](https://termbin.com/tqrb)
I was using Node 17.2 but downgrading to Node 14 (v14.18.3) with `nvm install 14` (I use [`nvm`](https://github.com/nvm-sh/nvm)), it builds with no issues

**Comment by pinheadmz** [comment]
Actually looks like the AppImage built by the github action also pins 1.0.0:

https://github.com/kyokan/bob-wallet/pull/383

So maybe we just need to update the README

**Comment by Thijxx** [comment]
The 0.9.0 release does not have an appImage in the assets, I'm running the RC1 now, works fine

**Comment by rithvikvibhu** [comment]
Hey @Thijxx, which OS are you running?
Can you try https://github.com/kyokan/bob-wallet/suites/4975633841/artifacts/145176999 (v0.9.0) and see if it works for you?

**Comment by Thijxx** [comment]
> 

Yes it works fine, like the RC.
I'm on Ubuntu 21.10
