### ISSUE TITLE
Needs app restart on toggling SPV mode

### ISSUE THREAD

**Issue by rithvikvibhu** [kyokan/bob-wallet#467]
<img width="1059" alt="Screen Shot 2022-02-08 at 1 18 08 PM" src="https://user-images.githubusercontent.com/2084648/153050767-fc27d9e0-3f3c-4d5d-8976-b756953b42e6.png">

Switching to SPV from this screen did lock up the app though. I had to restart it twice to get it to start syncing SPV. One thing that may be an issue swithcing from full node to SPV is the hosts.json file. I find that deleting this file gives the spv node a much better chance of finding supporting peers.

_Originally posted by @pinheadmz in https://github.com/kyokan/bob-wallet/issues/463#issuecomment-1032924871_

**Comment by lukeburns** [comment]
Fully syncing the SPV node before switching back to the full node fixed the stall.
