### ISSUE TITLE
Passphrase not validated for each signing request.

### ISSUE THREAD

**Issue by eskimo** [kyokan/bob-wallet#472]
When you sign a your first message, it properly validates your password, however on subsequent signings it presents the modal yet you can simply type anything as your passphrase and it will be accepted.

## Expected Behavior
Shouldn't sign if a wrong passphrase is entered

## Current Behavior
Signs regardless of what passphrase is entered

## Steps to Reproduce
1. Enter a message
2. Click sign
3. Enter your passphrase
4. Enter another message
5. Type in random text in the passphrase field

## Screencap
https://user-images.githubusercontent.com/12444228/154316349-d783295b-9171-4186-b01a-2a3dc3dd8896.mp4

**Comment by pinheadmz** [comment]
I think this has been discussed in other issues: when you enter your wallet passphrase, the wallet is "unlocked" for a default timeout of 60 seconds. During that time, anything can be signed with your private keys. Entering an incorrect passphrase during that time does NOT lock the wallet again. Completing a signature does NOT lock the wallet again.

**Comment by eskimo** [comment]
If that's the case, the modal should either 1. not show if the current state is unlocked, and/or 2. an invalid passphrase should lock it.
