### ISSUE TITLE
[request] retrieve account xpub from settings

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#479]
This should be considered an advanced action, but getting an xpub can be used for watch only wallets like https://github.com/pinheadmz/hip2-server

**Comment by pinheadmz** [comment]
bump!
Getting an xpub will also allow bob users to engage in multisig wallets, even though bob doesnt have multisig yet.

**Comment by magicstone1412** [comment]
Please make it happen for ledger also. Thank you
