### ISSUE TITLE
Can not set custom API key

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#484]
to reproduce:

- open bob
- go to settings > wallet
- set a custom API by typing in the text area
- restart bob (the modal says to restart for new api key to take effect)
- go back to settings and look at api key, its been randomly regenerated

**Comment by 0xStefan** [comment]
Just wanted to confirm that. Not working for me either

**Comment by rithvikvibhu** [comment]
@0xStefan can you try out #486? It should be able to set/use different api keys
