### ISSUE TITLE
Report issue button goes to old forum.kyokan.io

### ISSUE THREAD

**Issue by Nathanwoodburn** [kyokan/bob-wallet#503]
## Expected Behavior
The report issue in the navigation bar should point to an active help site.

## Current Behavior
The reportissue button links to an old link: https://forum.kyokan.io/c/bob/support/5

## Steps to Reproduce
1. Open bob
2. Click Help
3. Click Report Issue

## Context (Environment)
Just to provide easier ways to get help with bob

## Screencap
<img width="182" alt="image" src="https://user-images.githubusercontent.com/62039630/165515116-f2f76585-57f8-4c62-8c2c-c648d834e705.png">

**Comment by rithvikvibhu** [comment]
Been fixed by @Falci in #481.
