### ISSUE TITLE
Bid still pending during reveal period

### ISSUE THREAD

**Issue by nova8472** [kyokan/bob-wallet#505]
I have recently started an auction and bid 5 HNS with 35 HNS blind using bob wallet. After placing the bid, I closed the wallet and checked yesterday to reveal the bid. The reveal period had indeed started, but my bid with 40 HNS lock-up is still showing as pending in bob wallet. Bidding ends is shown as "~NaNd NaNh NaNm", and highest lock-up is 400 000.

Looking at the name with https://hnsnetwork.com/ I see that someone else placed a bid of 0.4 HNS, so 400 000 makes no sense.

In addition, in bob wallet my total balance is 100, but my spendable balance is 60. I cannot reveal my bid to get my lock-up back as it is still "pending" apparently.

![image](https://user-images.githubusercontent.com/9392904/165818315-dc4b1e48-17c5-4b32-b2c4-c4969282db28.png)

Does anyone have any idea how this happened and how I can get my lock-up back?

**Comment by rithvikvibhu** [comment]
Hey @nova8472

>The reveal period had indeed started, but my bid with 40 HNS lock-up is still showing as pending in bob wallet.

There are generally 2 reasons why it a tx would still be pending:
- It was not mined in time and with the bidding period ending, that bid remains as pending until zapped
- The node isn't synced completely. At a particular height that the node is at, it only knows about transactions till that block. If the node isn't fully synced, it's best to wait till it is (and then bid, or do other things)

In either case, if you see that the auction is already past the bidding period, that Bob is synced, and the tx is still pending, then it can be removed from the wallet from Settings -> Wallet -> Zap Pending Transactions.

>Looking at the name with https://hnsnetwork.com/ I see that someone else placed a bid of 0.4 HNS, so 400 000 makes no sense.

That's a UI bug, will take a look at it. The 400 000 is in dollarydoos (smallest unit - equivalent of sats in bitcoin) when it should be in whole HNS like other values on the page. But the value itself is correct (0.4 HNS) as that's the highest lockup from the bids table in your pic above.

>Bidding ends is shown as "~NaNd NaNh NaNm"

This was fixed 1-2 releases ago, will check again. Are you on the latest v0.9.0?
