### ISSUE TITLE
No bids to reveal after bidding twice

### ISSUE THREAD

**Issue by nova8472** [kyokan/bob-wallet#506]
## Expected Behavior
I bid on a name 2 months ago and later realized something went wrong and the bid did not register. Recently I realized the name was still available so I started a new auction and placed a bid. To my surprise, the auction had two bids now - both mine. The one I placed 2 months ago, and the one I placed now. However, when the reveal time came, Bob shows that there are no bids to reveal even though it shows I have two bids. 

I have participated in auctions successfully previously. However, I also faced this problem recently: https://github.com/kyokan/bob-wallet/issues/505

## Current Behavior

It looks like Bob has an issue placing bids sometimes. The names I tried to get had nothing uncommon (just Latin letters and digits). 

## Steps to Reproduce

It happened twice for the domain names "crysis4" and "mongodbcompass" (twice for each domain), but likely extremely difficult to reproduce reliably. 

## Screencap

![nobids](https://user-images.githubusercontent.com/9392904/165819615-e55480da-3988-43c4-bf24-dd3e4e78a35d.png)

**Comment by rithvikvibhu** [comment]
Looking at https://www.niami.io/domain/crysis4 gives a better picture of what happened:

The auction was opened on 19 Feb 2022, and got your bid (0.1 + 0 HNS). But that bid was never revealed during the 10-day reveal period and so not considered.

With no reveals, the name went back to its unauctioned state.

Then it was opened again on 21 Apr 2022. It got both bids - one of yours (0.1 + 0.99 HNS) and another of 25 HNS. Both were revealed.

>The one I placed 2 months ago, and the one I placed now. However, when the reveal time came, Bob shows that there are no bids to reveal even though it shows I have two bids.

So, the bid from the first auction cannot be revealed, it's burned already. Your second bid seems to be revealed already, hence the "No bids to reveal".

Bob should show bids only from the latest auction - let's keep this issue open until that's fixed.
