### ISSUE TITLE
Add an option to extend the log out automatically pop

### ISSUE THREAD

**Issue by miguelgargallo** [kyokan/bob-wallet#514]
Add an option to extend the log out automatically pop to:
Default, 10 minutes, 20 minutes or never with an alert warning users.

![Miguel Gargallo is the CEO of Pencil Domains, pencil domains is the 1st Europe Andorra Canarias Spain Registrar  Miguel Gargallo is telling to the world new fix for Bob Wallet development](https://user-images.githubusercontent.com/5947268/168794321-5e116ee3-0c3e-408b-b5f5-bb4e6af659e8.png)

**Comment by rithvikvibhu** [comment]
This already exists. Can set how much time of inactivity will lock the app (or set 0 to disable).
It's under Settings -> General.
