### ISSUE TITLE
wallet says not connected 

### ISSUE THREAD

**Issue by jithv198787** [kyokan/bob-wallet#523]
## Steps to Reproduce

1.
1.
1.
1.

**Comment by jithv198787** [comment]
![WhatsApp Image 2022-06-17 at 2 46 41 PM](https://user-images.githubusercontent.com/107573310/174268447-fe71e254-910d-48c8-bc91-dfa8e87dfbdd.jpeg)

**Comment by rithvikvibhu** [comment]
Followed up on Discord, it's the same as #453.
