### ISSUE TITLE
Failed wallet installation and browser  extension bremoved from Chrome store

### ISSUE THREAD

**Issue by edwardgrubb3rd** [kyokan/bob-wallet#536]
Bob Wallet 1.0.0 RC doesn't install on Windows 11 Enterprise. 

I also noticed that the browser extension has been removed from Chrome Store due to what they say is untrustworthy .

-Edward
@edwardgrubb3rd

**Comment by rithvikvibhu** [comment]
Hey @edwardgrubb3rd have any more info on why it doesn't install on Enterprise? Does it give an error?

btw, the extension is back in the store: https://chrome.google.com/webstore/detail/bob-extension/ogcmjchbmdichlfelhmceldndgmgpcem
