### ISSUE TITLE
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json

### ISSUE THREAD

**Issue by miguelgargallo** [kyokan/bob-wallet#545]
Sometimes when you install Bob on Ubuntu 21.04 LTS with Node 16.16.0 and nvm 0.39.1

## Log

john@host:~/Documents/bob-wallet$ npm i --legacy-peer-deps
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /home/john/.nvm/versions/node/v16.16.0/bin/node /home/john/.nvm/versions/node/v16.16.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/john/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > node-hid@2.1.1-hsd.0 install
npm ERR! > prebuild-install --runtime napi || node-gyp rebuild
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! sh: 1: prebuild-install: not found
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.16.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/john/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/john/.npm/_cacache/tmp/git-clonemqY9sQ/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/john/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/john/.cache/node-gyp/16.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/john/.cache/node-gyp/16.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/john/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/john/.cache/node-gyp/16.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/john/.npm/_cacache/tmp/git-clonemqY9sQ',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Package libusb-1.0 was not found in the pkg-config search path.
npm ERR! Perhaps you should add the directory containing `libusb-1.0.pc'
npm ERR! to the PKG_CONFIG_PATH environment variable
npm ERR! No package 'libusb-1.0' found
npm ERR! gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/john/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.4.0-124-generic
npm ERR! gyp ERR! command "/home/john/.nvm/versions/node/v16.16.0/bin/node" "/home/john/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/john/.npm/_cacache/tmp/git-clonemqY9sQ
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/john/.npm/_cacache/tmp/git-clonemqY9sQ
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c prebuild-install --runtime napi || node-gyp rebuild
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/john/.npm/_logs/2022-08-11T10_06_04_689Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john/.npm/_logs/2022-08-11T10_05_23_472Z-debug-0.log
john@host:~/Documents/bob-wallet$ sudo npm i --legacy-peer-deps
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> bcrypto@5.4.0 install /home/john/Documents/bob-wallet/node_modules/bcrypto
> node-gyp rebuild

make: Entering directory '/home/john/Documents/bob-wallet/node_modules/bcrypto/build'
  CC(target) Release/obj.target/torsion/deps/torsion/src/aead.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/asn1.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/cipher.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/drbg.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/dsa.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/ecc.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/encoding.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/entropy/env.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/entropy/hw.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/entropy/sys.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/hash.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/ies.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/internal.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/kdf.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/mac.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/mpi.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/rand.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/rsa.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/stream.o
  CC(target) Release/obj.target/torsion/deps/torsion/src/util.o
  AR(target) Release/obj.target/torsion.a
  COPY Release/torsion.a
  CC(target) Release/obj.target/secp256k1/deps/secp256k1/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/deps/secp256k1/src/secp256k1.o
  AR(target) Release/obj.target/secp256k1.a
  COPY Release/secp256k1.a
  CC(target) Release/obj.target/bcrypto/src/bcrypto.o
  SOLINK_MODULE(target) Release/obj.target/bcrypto.node
  COPY Release/bcrypto.node
make: Leaving directory '/home/john/Documents/bob-wallet/node_modules/bcrypto/build'

> bdb@1.4.0 install /home/john/Documents/bob-wallet/node_modules/bdb
> node-gyp rebuild

make: Entering directory '/home/john/Documents/bob-wallet/node_modules/bdb/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/dumpfile.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/db/version_edit.o

**Comment by rithvikvibhu** [comment]
>npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

That's a pretty old version of npm. Update it with `npm install -g npm`.

For the actual error, the README has a snippet to install dependencies:
```sh
sudo apt install libusb-1.0-0-dev libudev-dev
```
