### ISSUE TITLE
Chrome-extension no rescan

### ISSUE THREAD

**Issue by moringa303** [kyokan/bob-wallet#547]
Hello,

the bob wallet chrome extension doesn't perform the res-can. It's a endless loop.
The RCP URL https://5pi.io/hsd seems offline as well.

How to fix this ?

**Comment by rithvikvibhu** [comment]
Hey, you can use `https://api.handshakeapi.com/hsd` instead (it's the new default value).

**Comment by rithvikvibhu** [comment]
Closing this now. Feel free to open a new issue on https://github.com/kyokan/bob-extension if related to the extension :)

**Comment by moringa303** [comment]
Hi,

thanks for the mail. We wrote already on Telegram.
The problem is the wallet rescan does not work.
You can check the attached screenshot.

Best regards

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
