### ISSUE TITLE
Blind value not found

### ISSUE THREAD

**Issue by dwordz** [kyokan/bob-wallet#553]
When I am trying to reveal bids in Bob occasionally I get a pop up that the blind value can not be found and it will not reveal any bids. 
I have to go through and reveal each bid individually.
This time when I tried to reveal one at a time, I got a message saying Failed to reveal bid: Could not resolve preferred inputs.

I have had a similar issue when I have bid on one machine and revealed on another machine with the same wallet. I need to confirm those bids and then reveal will work as normal. I bid and revealed on the same computer this time.

## Expected Behavior

When I select reveal bids it should reveal all the bids that are available to reveal.

## Current Behavior

Now when I click Reveal bids and enter my password, I get a message that says Blind value not found.
Is there a way I can find the exact bid that is causing the problem? As of now I have to reveal each bid individually.
## Steps to Reproduce

1. Open Bob and click the light red box that says Reveal ## bids.
1.
1.
1.

**Comment by rithvikvibhu** [comment]
True, we need to exclude bids without values or show a preview before trying to send all.

The "Could not resolve preferred inputs" shouldn't appear once #546 is merged (for next version).

I don't think there's currently any way to view a list of all repairable bids in Bob directly.
If it's a small number, then can check each name's auction page (from Your Bids page).

If it's a huge number, you can use this script for now that lists all repairable bids:
1. Requires nodejs installed already
2. create a new folder and download this file into it: https://gist.github.com/rithvikvibhu/8541adcf90ea94d8127a38b91dfad8d3
3. Edit the 2 lines at top of file (api key from Bob and wallet name)
4. Install hsd (as a library, no need to run it): `npm install hsd`
5. Run the script: `node missing-blind-bids.js`

It should display 2 pretty tables:
- Lost bids with unknown true bid values (too late to reveal)
- Active bids with unknown true bid values (repair them to reveal!)

**Comment by JackGordon** [comment]
Is there an rpc command or other way to repair a lot of bids with the same value?

**Comment by rithvikvibhu** [comment]
@JackGordon you'll have to script through that. There's an rpc command to repair a single bid: https://hsd-dev.org/api-docs/?shell--cli#importnonce which you can call for bids that you want to repair

**Comment by rithvikvibhu** [comment]
v2.0.0 reveals bids that have blinds without erroring when there are bids without blinds.
