### ISSUE TITLE
HNS not deposited in my Bob Wallet 

### ISSUE THREAD

**Issue by 12omi** [kyokan/bob-wallet#559]
I withdrew $HNS on Gate.io but it never deposited into my Bob wallet. For evidence, I'll provide details of the transaction. 
## Current Behavior

I have firstly attached proof of the withdrawal from my Gate.io account. Furthermore, i have attached proof that the $HNS address the $HNS was sent to from Gate.io are the same. 
![Proof of withdrawal - $HNS](https://user-images.githubusercontent.com/113641625/190513437-3b9038db-e490-4e72-968f-995374b19b46.png)
![Verification of address](https://user-images.githubusercontent.com/113641625/190513490-238551c1-cd9b-42bf-98e8-5651363226f7.png)
## Steps to Reproduce

1.
1.
1.
1.

**Comment by rithvikvibhu** [comment]
Hey @12omi did the deposit show up in Bob?

>Furthermore, i have attached proof that the $HNS address the $HNS was sent to from Gate.io are the same.

They're not the same though? If you're sure that the address matched at that time, then a new address here means the wallet saw that the old address was used (i.e. Gate sent the tx and the wallet got it) and generated a new one on the Receive page. The Balance should have updated.
