### ISSUE TITLE
i can't redeem my bid and can't register

### ISSUE THREAD

**Issue by haquebasheer** [kyokan/bob-wallet#560]
## Steps to Reproduce

1.
1.
1.
1.

**Comment by rithvikvibhu** [comment]
What's the issue / is there any error?

**Comment by haquebasheer** [comment]
Yeah there error in registering names which I won in bob wallet still it's
pending from first of the current month. What I do? Please clear issue

**Comment by rithvikvibhu** [comment]
Closing as resolved in chat.
