### ISSUE TITLE
Configuring a external node?

### ISSUE THREAD

**Issue by 0xBadMad** [kyokan/bob-wallet#562]
Is it possible for someone to explain how to add an external node. I have a full node running on some of our co-lo servers, and seeing that I have a smaller ssd on my travel laptop, my preference would be to use that full node while using Bob Wallet. I relied on Namebase up until now, but the trust has been damaged so I would like to have this as the alternative. Sorry I know I am not as well versed as most of you, that is why I usually call my inhouse developers for this, but I am on the road, and determined to learn some of this myself.

**Comment by rithvikvibhu** [comment]
(assuming you're talking about one Bob Wallet desktop app using another node which can be hsd, another Bob, etc.)

In Settings -> Network & Connections, there's an option to set an RPC. Enter the IP address/hostname, port and api key and Bob will test to see if it can connect to that node.
