### ISSUE TITLE
Stuck at 99.79% during rescan

### ISSUE THREAD

**Issue by dis0wned** [kyokan/bob-wallet#563]
During a rescan, my wallet hung overnight and never cleared up
## Current Behavior

It will not finish rescan
## Steps to Reproduce

1.
1.
1.
1.

## Logs

[D:2022-09-24T19:49:33Z] (wallet-http) Request for method=GET path=/wallet/sadf (127.0.0.1).
[D:2022-09-24T19:49:33Z] (wallet-http) Request for method=POST path=/wallet/sadf/unlock (127.0.0.1).
[E:2022-09-24T19:49:33Z] (node) Could not decrypt.
    at Object.decipher (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bcrypto\lib\native\aes.js:50:36)
    at MasterKey._unlock (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\hsd\lib\wallet\masterkey.js:171:22)
    at async MasterKey.unlock (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\hsd\lib\wallet\masterkey.js:142:14)
    at async Route.handler (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\hsd\lib\wallet\http.js:385:7)
    at async Router.handle (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\router.js:100:9)
    at async HTTP._handleStack (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\server.js:294:9)
    at async HTTP._handleRequest (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\server.js:203:9)
    at async Server.<anonymous> (C:\Users\replaced\AppData\Local\Programs\bob-wallet\resources\app.asar\node_modules\bweb\lib\server.js:126:9)
[D:2022-09-24T19:49:58Z] (peer) Peer has not responded to ping (207.244.233.76:12038).
[D:2022-09-24T19:49:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:49:58Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:49:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:50:10Z] (wallet-http) Request for method=GET path=/wallet/sadf (127.0.0.1).
[D:2022-09-24T19:50:10Z] (wallet-http) Request for method=POST path=/wallet/sadf/unlock (127.0.0.1).
[D:2022-09-24T19:50:11Z] (wallet-http) Request for method=GET path=/wallet/sadf (127.0.0.1).
[D:2022-09-24T19:50:11Z] (wallet-http) Request for method=GET path=/wallet/sadf (127.0.0.1).
[D:2022-09-24T19:50:11Z] (wallet-http) Request for method=GET path=/wallet/sadf/master (127.0.0.1).
[D:2022-09-24T19:50:11Z] (wallet-http) Request for method=GET path=/wallet/sadf (127.0.0.1).
[D:2022-09-24T19:50:11Z] (wallet-http) Request for method=POST path=/wallet/sadf/lock (127.0.0.1).
[D:2022-09-24T19:50:11Z] (node-rpc) Handling RPC call: getblockchaininfo.
[D:2022-09-24T19:50:11Z] (node-rpc) []
[D:2022-09-24T19:50:11Z] (node-http) Request for method=GET path=/ (127.0.0.1).
[D:2022-09-24T19:50:18Z] (net) Error: Peer is stalling (block). (207.244.233.76:12038)
[I:2022-09-24T19:50:18Z] (net) Removed loader peer (207.244.233.76:12038).
[I:2022-09-24T19:50:19Z] (net) Repurposing peer for loader (31.222.229.163:12038).
[D:2022-09-24T19:50:19Z] (net) Connecting to 185.234.52.206:12038.
[I:2022-09-24T19:50:19Z] (net) Connected to 185.234.52.206:12038.
[D:2022-09-24T19:50:20Z] (peer) Received verack (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (net) Received version (185.234.52.206:12038): version=3 height=139090 services=11 agent=/hsd:4.0.2/ape.c/
[D:2022-09-24T19:50:20Z] (node) Added time data: samples=5, offset=0 (0 minutes).
[I:2022-09-24T19:50:20Z] (node) Time offset: 0 (0 minutes).
[D:2022-09-24T19:50:20Z] (peer) Version handshake complete (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (peer) Initializing normal compact blocks (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (net) Received 176 addrs (hosts=611, peers=4) (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (peer) Peer initialized compact blocks (mode=0, version=1) (185.234.52.206:12038).
[D:2022-09-24T19:50:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:50:28Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:50:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:50:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:50:58Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:50:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:51:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:51:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:51:28Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:51:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:51:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:51:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:51:58Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:51:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:52:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:52:24Z] (net) Error: Peer is stalling (block). (31.222.229.163:12038)
[I:2022-09-24T19:52:24Z] (net) Removed loader peer (31.222.229.163:12038).
[I:2022-09-24T19:52:26Z] (net) Repurposing peer for loader (204.99.129.8:12038).
[D:2022-09-24T19:52:26Z] (net) Connecting to 82.223.165.215:12038.
[I:2022-09-24T19:52:26Z] (net) Connected to 82.223.165.215:12038.
[D:2022-09-24T19:52:26Z] (peer) Received verack (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (net) Received version (82.223.165.215:12038): version=3 height=139090 services=11 agent=/hsd:4.0.0/ape.c/
[D:2022-09-24T19:52:26Z] (node) Added time data: samples=6, offset=0 (0 minutes).
[D:2022-09-24T19:52:26Z] (peer) Version handshake complete (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (peer) Initializing normal compact blocks (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (peer) Peer initialized compact blocks (mode=0, version=1) (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (net) Received 176 addrs (hosts=611, peers=4) (82.223.165.215:12038).
[D:2022-09-24T19:52:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:52:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:52:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:52:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:52:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:53:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:53:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:53:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:53:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:53:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:53:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:53:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:53:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:54:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:54:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:54:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:54:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:54:29Z] (net) Error: Peer is stalling (block). (204.99.129.8:12038)
[I:2022-09-24T19:54:29Z] (net) Removed loader peer (204.99.129.8:12038).
[I:2022-09-24T19:54:29Z] (net) Repurposing peer for loader (212.227.68.123:12038).
[D:2022-09-24T19:54:29Z] (net) Connecting to 77.160.165.78:12038.
[D:2022-09-24T19:54:34Z] (net) Error: Connection timed out. (77.160.165.78:12038)
[D:2022-09-24T19:54:35Z] (net) Connecting to 152.69.186.119:12038.
[I:2022-09-24T19:54:36Z] (net) Connected to 152.69.186.119:12038.
[D:2022-09-24T19:54:36Z] (peer) Received verack (152.69.186.119:12038).
[I:2022-09-24T19:54:36Z] (net) Received version (152.69.186.119:12038): version=3 height=139090 services=11 agent=/hsd:4.0.2/
[D:2022-09-24T19:54:36Z] (node) Added time data: samples=7, offset=0 (0 minutes).
[I:2022-09-24T19:54:36Z] (node) Time offset: 0 (0 minutes).
[D:2022-09-24T19:54:36Z] (peer) Version handshake complete (152.69.186.119:12038).
[I:2022-09-24T19:54:36Z] (peer) Initializing normal compact blocks (152.69.186.119:12038).
[I:2022-09-24T19:54:37Z] (net) Received 174 addrs (hosts=611, peers=4) (152.69.186.119:12038).
[I:2022-09-24T19:54:37Z] (peer) Peer initialized compact blocks (mode=0, version=1) (152.69.186.119:12038).
[D:2022-09-24T19:54:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:54:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:54:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:55:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:55:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:55:27Z] (hostlist) Writing hosts to C:\Users\replaced\AppData\Roaming\Bob\hsd_data\hosts.json.
[D:2022-09-24T19:55:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:55:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:55:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:55:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:55:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:56:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:56:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:56:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:56:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:56:30Z] (net) Error: Peer is stalling (block). (212.227.68.123:12038)
[I:2022-09-24T19:56:30Z] (net) Removed loader peer (212.227.68.123:12038).
[I:2022-09-24T19:56:30Z] (net) Repurposing peer for loader (185.234.52.206:12038).
[D:2022-09-24T19:56:30Z] (net) Connecting to 66.94.118.127:12038.
[D:2022-09-24T19:56:35Z] (net) Error: Connection timed out. (66.94.118.127:12038)
[D:2022-09-24T19:56:36Z] (net) Connecting to 159.69.46.23:12038.
[D:2022-09-24T19:56:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[I:2022-09-24T19:56:36Z] (net) Connected to 159.69.46.23:12038.
[D:2022-09-24T19:56:36Z] (peer) Received verack (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (net) Received version (159.69.46.23:12038): version=3 height=139090 services=11 agent=/hsd:4.0.0/
[D:2022-09-24T19:56:36Z] (node) Added time data: samples=8, offset=0 (0 minutes).
[D:2022-09-24T19:56:36Z] (peer) Version handshake complete (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (peer) Initializing normal compact blocks (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (peer) Peer initialized compact blocks (mode=0, version=1) (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (net) Received 91 addrs (hosts=611, peers=4) (159.69.46.23:12038).
[D:2022-09-24T19:56:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:56:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:57:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:57:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:57:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:57:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:57:36Z] (peer) Peer has not responded to ping (159.69.46.23:12038).
[D:2022-09-24T19:57:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:57:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:58:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:58:06Z] (peer) Peer has not responded to ping (159.69.46.23:12038).
[D:2022-09-24T19:58:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:58:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:58:31Z] (net) Error: Peer is stalling (block). (185.234.52.206:12038)
[I:2022-09-24T19:58:31Z] (net) Removed loader peer (185.234.52.206:12038).
[I:2022-09-24T19:58:34Z] (net) Repurposing peer for loader (82.223.165.215:12038).
[D:2022-09-24T19:58:34Z] (net) Connecting to 15.152.112.161:12038.
[D:2022-09-24T19:58:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:58:36Z] (peer) Peer has not responded to ping (159.69.46.23:12038).
[D:2022-09-24T19:58:39Z] (net) Error: Connection timed out. (15.152.112.161:12038)
[D:2022-09-24T19:58:40Z] (net) Connecting to 149.102.152.193:12038.
[I:2022-09-24T19:58:40Z] (net) Connected to 149.102.152.193:12038.
[D:2022-09-24T19:58:40Z] (peer) Received verack (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (net) Received version (149.102.152.193:12038): version=3 height=139090 services=11 agent=/hsd:4.0.0/ape.c/
[D:2022-09-24T19:58:40Z] (node) Added time data: samples=9, offset=0 (0 minutes).
[I:2022-09-24T19:58:40Z] (node) Time offset: 0 (0 minutes).
[D:2022-09-24T19:58:40Z] (peer) Version handshake complete (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (peer) Initializing normal compact blocks (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (peer) Peer initialized compact blocks (mode=0, version=1) (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (net) Received 149 addrs (hosts=611, peers=4) (149.102.152.193:12038).
[D:2022-09-24T19:58:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:59:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:59:06Z] (peer) Peer has not responded to ping (159.69.46.23:12038).

**Comment by dis0wned** [comment]
[D:2022-09-24T19:50:20Z] (peer) Received verack (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (net) Received version (185.234.52.206:12038): version=3 height=139090 services=11 agent=/hsd:4.0.2/ape.c/
[D:2022-09-24T19:50:20Z] (node) Added time data: samples=5, offset=0 (0 minutes).
[I:2022-09-24T19:50:20Z] (node) Time offset: 0 (0 minutes).
[D:2022-09-24T19:50:20Z] (peer) Version handshake complete (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (peer) Initializing normal compact blocks (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (net) Received 176 addrs (hosts=611, peers=4) (185.234.52.206:12038).
[I:2022-09-24T19:50:20Z] (peer) Peer initialized compact blocks (mode=0, version=1) (185.234.52.206:12038).
[D:2022-09-24T19:50:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:50:28Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:50:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:50:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:50:58Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:50:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:51:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:51:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:51:28Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:51:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:51:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:51:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:51:58Z] (peer) Peer has not responded to ping (31.222.229.163:12038).
[D:2022-09-24T19:51:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:52:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:52:24Z] (net) Error: Peer is stalling (block). (31.222.229.163:12038)
[I:2022-09-24T19:52:24Z] (net) Removed loader peer (31.222.229.163:12038).
[I:2022-09-24T19:52:26Z] (net) Repurposing peer for loader (204.99.129.8:12038).
[D:2022-09-24T19:52:26Z] (net) Connecting to 82.223.165.215:12038.
[I:2022-09-24T19:52:26Z] (net) Connected to 82.223.165.215:12038.
[D:2022-09-24T19:52:26Z] (peer) Received verack (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (net) Received version (82.223.165.215:12038): version=3 height=139090 services=11 agent=/hsd:4.0.0/ape.c/
[D:2022-09-24T19:52:26Z] (node) Added time data: samples=6, offset=0 (0 minutes).
[D:2022-09-24T19:52:26Z] (peer) Version handshake complete (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (peer) Initializing normal compact blocks (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (peer) Peer initialized compact blocks (mode=0, version=1) (82.223.165.215:12038).
[I:2022-09-24T19:52:26Z] (net) Received 176 addrs (hosts=611, peers=4) (82.223.165.215:12038).
[D:2022-09-24T19:52:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:52:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:52:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:52:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:52:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:53:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:53:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:53:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:53:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:53:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:53:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:53:58Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:53:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:54:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:54:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:54:28Z] (peer) Peer has not responded to ping (204.99.129.8:12038).
[D:2022-09-24T19:54:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:54:29Z] (net) Error: Peer is stalling (block). (204.99.129.8:12038)
[I:2022-09-24T19:54:29Z] (net) Removed loader peer (204.99.129.8:12038).
[I:2022-09-24T19:54:29Z] (net) Repurposing peer for loader (212.227.68.123:12038).
[D:2022-09-24T19:54:29Z] (net) Connecting to 77.160.165.78:12038.
[D:2022-09-24T19:54:34Z] (net) Error: Connection timed out. (77.160.165.78:12038)
[D:2022-09-24T19:54:35Z] (net) Connecting to 152.69.186.119:12038.
[I:2022-09-24T19:54:36Z] (net) Connected to 152.69.186.119:12038.
[D:2022-09-24T19:54:36Z] (peer) Received verack (152.69.186.119:12038).
[I:2022-09-24T19:54:36Z] (net) Received version (152.69.186.119:12038): version=3 height=139090 services=11 agent=/hsd:4.0.2/
[D:2022-09-24T19:54:36Z] (node) Added time data: samples=7, offset=0 (0 minutes).
[I:2022-09-24T19:54:36Z] (node) Time offset: 0 (0 minutes).
[D:2022-09-24T19:54:36Z] (peer) Version handshake complete (152.69.186.119:12038).
[I:2022-09-24T19:54:36Z] (peer) Initializing normal compact blocks (152.69.186.119:12038).
[I:2022-09-24T19:54:37Z] (net) Received 174 addrs (hosts=611, peers=4) (152.69.186.119:12038).
[I:2022-09-24T19:54:37Z] (peer) Peer initialized compact blocks (mode=0, version=1) (152.69.186.119:12038).
[D:2022-09-24T19:54:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:54:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:54:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:55:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:55:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:55:27Z] (hostlist) Writing hosts to C:\Users\dis0wned\AppData\Roaming\Bob\hsd_data\hosts.json.
[D:2022-09-24T19:55:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:55:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:55:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:55:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:55:58Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:56:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:56:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:56:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:56:28Z] (peer) Peer has not responded to ping (212.227.68.123:12038).
[D:2022-09-24T19:56:30Z] (net) Error: Peer is stalling (block). (212.227.68.123:12038)
[I:2022-09-24T19:56:30Z] (net) Removed loader peer (212.227.68.123:12038).
[I:2022-09-24T19:56:30Z] (net) Repurposing peer for loader (185.234.52.206:12038).
[D:2022-09-24T19:56:30Z] (net) Connecting to 66.94.118.127:12038.
[D:2022-09-24T19:56:35Z] (net) Error: Connection timed out. (66.94.118.127:12038)
[D:2022-09-24T19:56:36Z] (net) Connecting to 159.69.46.23:12038.
[D:2022-09-24T19:56:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[I:2022-09-24T19:56:36Z] (net) Connected to 159.69.46.23:12038.
[D:2022-09-24T19:56:36Z] (peer) Received verack (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (net) Received version (159.69.46.23:12038): version=3 height=139090 services=11 agent=/hsd:4.0.0/
[D:2022-09-24T19:56:36Z] (node) Added time data: samples=8, offset=0 (0 minutes).
[D:2022-09-24T19:56:36Z] (peer) Version handshake complete (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (peer) Initializing normal compact blocks (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (peer) Peer initialized compact blocks (mode=0, version=1) (159.69.46.23:12038).
[I:2022-09-24T19:56:36Z] (net) Received 91 addrs (hosts=611, peers=4) (159.69.46.23:12038).
[D:2022-09-24T19:56:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:56:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:57:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:57:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:57:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:57:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:57:36Z] (peer) Peer has not responded to ping (159.69.46.23:12038).
[D:2022-09-24T19:57:50Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:57:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:58:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:58:06Z] (peer) Peer has not responded to ping (159.69.46.23:12038).
[D:2022-09-24T19:58:20Z] (peer) Peer has not responded to ping (185.234.52.206:12038).
[D:2022-09-24T19:58:26Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:58:31Z] (net) Error: Peer is stalling (block). (185.234.52.206:12038)
[I:2022-09-24T19:58:31Z] (net) Removed loader peer (185.234.52.206:12038).
[I:2022-09-24T19:58:34Z] (net) Repurposing peer for loader (82.223.165.215:12038).
[D:2022-09-24T19:58:34Z] (net) Connecting to 15.152.112.161:12038.
[D:2022-09-24T19:58:36Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:58:36Z] (peer) Peer has not responded to ping (159.69.46.23:12038).
[D:2022-09-24T19:58:39Z] (net) Error: Connection timed out. (15.152.112.161:12038)
[D:2022-09-24T19:58:40Z] (net) Connecting to 149.102.152.193:12038.
[I:2022-09-24T19:58:40Z] (net) Connected to 149.102.152.193:12038.
[D:2022-09-24T19:58:40Z] (peer) Received verack (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (net) Received version (149.102.152.193:12038): version=3 height=139090 services=11 agent=/hsd:4.0.0/ape.c/
[D:2022-09-24T19:58:40Z] (node) Added time data: samples=9, offset=0 (0 minutes).
[I:2022-09-24T19:58:40Z] (node) Time offset: 0 (0 minutes).
[D:2022-09-24T19:58:40Z] (peer) Version handshake complete (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (peer) Initializing normal compact blocks (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (peer) Peer initialized compact blocks (mode=0, version=1) (149.102.152.193:12038).
[I:2022-09-24T19:58:40Z] (net) Received 149 addrs (hosts=611, peers=4) (149.102.152.193:12038).
[D:2022-09-24T19:58:56Z] (peer) Peer has not responded to ping (82.223.165.215:12038).
[D:2022-09-24T19:59:06Z] (peer) Peer has not responded to ping (152.69.186.119:12038).
[D:2022-09-24T19:59:06Z] (peer) Peer has not responded to ping (159.69.46.23:12038).

**Comment by ElHoussainBouhyla** [comment]
hi @dis0wned i have the same problem can you tell how you solve it pls?
