### ISSUE TITLE
Please help me to Open my wallet 

### ISSUE THREAD

**Issue by haquebasheer** [kyokan/bob-wallet#564]
## Expected Behavior

![szyxyujfc](https://user-images.githubusercontent.com/95602448/192959586-513b97a2-7da4-4794-abae-763b0daa94c6.png)
![gshjudk](https://user-images.githubusercontent.com/95602448/192959704-274a565c-0771-4355-9a56-aad1b662cef5.png)

## Steps to Reproduce

1.
1.
1.
1.

**Comment by rithvikvibhu** [comment]
Think we resolved this in chat, it was exchange_db that was corrupted. Feel free to reopen if it happens again.
