### ISSUE TITLE
My bobwallet won't sync, don't know why

### ISSUE THREAD

**Issue by ForestCoin** [kyokan/bob-wallet#565]
Something went wrong fetching this name. Please try again.
Oops! Would you mind telling us what went wrong?

My bobwallet won't sync, don't know why

**Comment by rithvikvibhu** [comment]
Hey @ForestCoin that's weird. Is this still happening? If yes,
- Which version of Bob is this on?
- What's the sync status (percentage and height)?
- Is the height changing?
- Is SPV mode enabled (it's disabled by default)

**Comment by rithvikvibhu** [comment]
If updating to the latest version v2.0.0 doesn't fix this sync issue, feel free to re-open this.
