### ISSUE TITLE
impossible to reveal many bids and 

### ISSUE THREAD

**Issue by TchikTchakX** [kyokan/bob-wallet#567]
Hello,
I use bob wallet.
I have several auctions that are blocked. Arrivals at the end of the time, an auction does not pass.
It is therefore impossible to reveal the bids to recover the hns.
should I wait for the end of the reveal? or can I do something else to fix this.?

I have a large amount locked in several auction unfinished.
here a screenpics of one of them.

Thanks in advance.
Kind regards

Tchiktchak

![Capture d’écran 2022-10-06 185438](https://user-images.githubusercontent.com/103219115/194373145-2df9ef02-730a-4da5-b95a-8c52ba9d9b05.png)

**Comment by TchikTchakX** [comment]
> Hello, I use bob wallet. I have several auctions that are blocked. Arrivals at the end of the time, an auction does not pass. It is therefore impossible to reveal the bids to recover the hns. should I wait for the end of the reveal? or can I do something else to fix this.?
> 
> I have a large amount locked in several auction unfinished. here a screenpics of one of them.
> 
> Thanks in advance. Kind regards
> 
> Tchiktchak
> 
> ![Capture d’écran 2022-10-06 185438](https://user-images.githubusercontent.com/103219115/194373145-2df9ef02-730a-4da5-b95a-8c52ba9d9b05.png)



🤗🥳🤗🥳🤗🥳🤗
Hello Guys,

I just want to let know that I have my problem resolved. 🤓

Thanks
Regards.

TchikTchak.

**Comment by rithvikvibhu** [comment]
Hey @TchikTchakX is this in the latest Bob Wallet? Iirc, this was fixed in v1.
