### ISSUE TITLE
Unable to change wallet via logout after "Compacting Urkel Tree"

### ISSUE THREAD

**Issue by befranz** [kyokan/bob-wallet#568]
After start of Bob 1.0.0 (on Mac) and "Compacting Urkel Tree" which took about 5 minutes on a Macbook M1 (with very fast NVME) I was unable to change wallet (no reaction after clicking on logout). After quit/start program behavior was normal again.

Additional notice: Usually this notebook and Bob run several days without restart/shutdwon/sleeping mode. This time (before new start und then compacting) Bob didn't run when I logged in. Probably crashed because of the pending compacting?

**Comment by rithvikvibhu** [comment]
>After start of Bob 1.0.0 (on Mac) and "Compacting Urkel Tree" which took about 5 minutes on a Macbook M1 (with very fast NVME) I was unable to change wallet (no reaction after clicking on logout).

Tried a few things but could not reproduce this. Only things I can think of is Bob (as an app) was frozen somehow (was it only logout not working or even other buttons, etc.?). Could be due to low memory idk

>Usually this notebook and Bob run several days without restart/shutdwon/sleeping mode. This time (before new start und then compacting) Bob didn't run when I logged in. Probably crashed because of the pending compacting?

Compaction will just continue where it left off so can safely close while it's compacting also. Is it still not starting now? Starting Bob from a terminal will show what the issue is in most cases.

**Comment by befranz** [comment]
> Tried a few things but could not reproduce this. Only things I can think of is Bob (as an app) was frozen somehow (was it only logout not working or even other buttons, etc.?). Could be due to low memory idk

App wasn't frozen, only logout didn't work. Device has 16GB RAM but yes, low memory can be a reason, on average 70-90% of memory is used.
And actually it was a one time issue, since restart Bob is working properly again.

**Comment by rithvikvibhu** [comment]
If this does happen again (on Bob v2+), feel free to re-open this. With a reproducible case, we can maybe figure out what's going on.
