### ISSUE TITLE
Add message on enabling SPV to restart Bob

### ISSUE THREAD

**Issue by Nathanwoodburn** [kyokan/bob-wallet#571]
## Expected Behavior

Bob should show a message saying "SPV mode Enabled. Please restart Bob to apply changes." on enabling SPV
Bob should show a message saying "SPV mode Disabled. Please restart Bob to apply changes." on disabling SPV

## Current Behavior

New users are wondering why there wallet doesn't sync anymore.

## Steps to Reproduce

1. Enable or Disable SPV mode

## Context (Environment)

This is just an ease of use request for new users.

**Comment by rithvikvibhu** [comment]
Switching to SPV and back shouldn't need a Bob restart (the node automatically does in the background).
Let's keep this open until that's fixed.

**Comment by rithvikvibhu** [comment]
Toggling SPV doesn't need Bob restarts anymore.
