### ISSUE TITLE
Registered domains are not showing

### ISSUE THREAD

**Issue by sauravkumarbir** [kyokan/bob-wallet#573]
Hello Bob  i have registered 20 domains i can't see any registered domains on my bob wallet domain manager. The domain's are showing but from today i can't see any domain's.

**Comment by rithvikvibhu** [comment]
@sauravkumarbir hey are the domains still not visible? Is Bob fully synced? What version of Bob is this?

The only way I can think of for domains to disappear is during a rescan or when importing a wallet in a new Bob.

**Comment by sauravkumarbir** [comment]
I was rescanning my wallet after I can't see my Domain's

**Comment by rithvikvibhu** [comment]
Oh yeah so all the txs, domains and balance will be shown as of the rescan height (and will keep changing as it goes through the wallet history). Once fully synced, everything should show up accurately.

**Comment by rithvikvibhu** [comment]
If the domains didn't show up even even after the rescan completed, feel free to re-open this.
