### ISSUE TITLE
language error

### ISSUE THREAD

**Issue by fremgang** [kyokan/bob-wallet#574]
## Steps to Reproduce

1.
1.
1.
1.

## Screencap

![image](https://user-images.githubusercontent.com/89713349/197086120-53db012d-20d1-4660-a1ea-79ba4addadd2.png)

**Comment by rithvikvibhu** [comment]
Bob Wallet only works with English seed phrases currently. For now, it's possible to import wallets with other language seed phrases with hsw-cli: https://hsd-dev.org/api-docs/?shell--cli#create-a-wallet
