### ISSUE TITLE
Github actions node version upgrade

### ISSUE THREAD

**Issue by Nathanwoodburn** [kyokan/bob-wallet#577]
This isn't a bug (but I can't seem to create other issues types)

Github has depreciated node.js 12. So we should update Bob to node.js 16
I'm not sure if this will change anything or is just quick fix.
See https://github.com/kyokan/bob-wallet/actions/runs/3326674191 and https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

## Screencap
![image](https://user-images.githubusercontent.com/62039630/200456609-abda312e-6999-4548-b06b-7b9238011a50.png)

**Comment by rithvikvibhu** [comment]
That's weird, we already use only node 16 in both workflow files. Not sure where that's coming from.
