### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by abutler69** [kyokan/bob-wallet#596]
https://i.imgur.com/yqDjlev.png
can you add what domains need attention when I get the pop up message "need to finalize 1 domain" and "register 1 domain"
![image](https://user-images.githubusercontent.com/81709905/215483759-a921bcd7-2e60-4b3f-9428-61fbe65815ad.png)

**Comment by rithvikvibhu** [comment]
thanks for creating this, we're tracking it in #593
