### ISSUE TITLE
Portfolio shows bids to reveal that are not there.

### ISSUE THREAD

**Issue by JohnMK1965** [kyokan/bob-wallet#619]
## Expected Behaviour
There are a number of coloured tabs at the top of the BoB portfolio. - They represent awaiting action. The account holder executes on these actions by clicking the tab and entering their password when prompted. Examples of tabs are: Reveal , Redeem, Register, Finalize etc.
Once the account holder has entered their password, they are usually met with a message to say the action will be completed in the next block. Once the action has completed by the end of the next block, the tab disappears,

## Current Behaviour
After the password was entered, it was followed by an 'oops, something went wrong' message which invited me to generate a bug report, directed me to log into GitHub and here I am!

## Steps to Reproduce
In context, this is not possible.

## Context (Environment)
It creates confusion around the current status of TLDs owned/invested in.

![image](https://user-images.githubusercontent.com/113527065/227919799-4a9c3767-ed7b-4841-89df-794b1ffda022.png)

**Comment by rithvikvibhu** [comment]
These were bids not yet repaired after wallet import. Both repaired and revealed, marking as closed, resolved in chat.
