### ISSUE TITLE
Receiving an error when attempting to view certain names

### ISSUE THREAD

**Issue by crymzyn** [kyokan/bob-wallet#623]
When I attempt to view certain names in Bob, I receive an error of "Something went wrong fetching this name. Please try again."  This was happening in v1, so I just updated to v2 and it is still happening.

## Expected Behavior
The names should be able to be viewed like any other name.

## Current Behavior
Unable to view certain names.

## Steps to Reproduce
1. Attempt to view the name "curb"
2. Attempt to view the name "chaser"
3. Note that neither name loads.
4. Attempt to view the name "tckr" (control)
5. Note that it loads as expected.

## Context (Environment)
I did notice the two names that are not working were previously expired and then re-auctioned.  That might help find the issue.

## Logs
I do not see anything in logs.

## Screencap
I can provide, just let me know what is needed.

**Comment by crymzyn** [comment]
Now I'm having issues doing a reveal on xn--228h51c/

I get an error of "Nothing to do" and now cannot view that name either.  

I have completely wiped the ~/.config/Bob folder multiple times, reimporting my wallet each time via seed phrase, and both version 1.0.0 and 2.0.0 have issues.

**Comment by crymzyn** [comment]
Seems like maybe SPV mode was the issue.  I am having better luck with it turned off.

**Comment by rithvikvibhu** [comment]
SPV depends on some infra that wasn't working for a few days last month around the time of this issue. It's fixed now, so if this happens again, feel free to re-open or create a new one.
