### ISSUE TITLE
Sending coins

### ISSUE THREAD

**Issue by chrisg31** [kyokan/bob-wallet#84]
I am trying to send coins from Bob to Namebase, but I get an error message:

"Something went wrong, please try again."

Any ideas?

version 0.2.3 of Bob wallet (using Windows OS)

**Comment by mslipper** [comment]
Hi there,

Do you have enough balance to send the coins + the fee?

**Comment by chrisg31** [comment]
Yup, I have over 4000 coins ^_^

**Comment by mslipper** [comment]
Ah - if these are mining rewards, they may need to reach coinbase maturity prior to being sendable. In which block number did you mine these coins?

**Comment by chrisg31** [comment]
If I put my cursor over the 02/14/20 it says 10:30 am, how does one calculate cb maturity?

I know I got these coins from the handshake airdrop, put my seed phrase into the import part of the Bob wallet, and today when I loaded my wallet it was not 0 anymore :-)  Just need to figure out how to send it now

**Comment by mslipper** [comment]
Are you comfortable with the command line? I'd like you to run some commands to see if this is a UI issue, something going on in HSD.

Separately - it looks like you're on Windows, which doesn't have a 0.2.4 build yet. 0.2.4 fixes an issue with HSD rejecting certain mempool transactions. I can cut a 0.2.4 Windows build in about an hour, which may fix the issue.

**Comment by chrisg31** [comment]
Thanks yes 0.2.4 hopefully will help

I would be happy to run command line, do you mean in DOS for Windows?
Should I download any other files or install anything to make this happen?

**Comment by mslipper** [comment]
Ah, DOS for Windows is a bit tricky (the `hs-client` libraries are a bit finnicky on there). I'll cut the 0.2.4 build now. Give that a shot, and if that doesn't work let's hop on Telegram or something and figure out what's going on.

**Comment by mslipper** [comment]
Ok, the Windows build is up. Try that - also try reducing the amount you're sending slightly since I have a hunch that fee estimation may be off.

**Comment by chrisg31** [comment]
Ok I tried 22 HNS and still got the same error message

**Comment by mslipper** [comment]
Hey there,

After digging a bit deeper it looks like this is related to coinbase maturity. Please see this forum post: https://forum.kyokan.io/t/urgent-announcement-unspendable-airdrop-claims/37 for more info. In the meantime, your coins should become spendable in about 100 blocks.

**Comment by mslipper** [comment]
Hi @chrisg31 -

I'm closing this for now, please reopen if your issue persists.
