### ISSUE TITLE
0 Balance but Wallet State says "Synchronized" 

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#85]
When importing an address with a non-zero balance, the wallet state says "Synchronized", but the balance remains at zero for up to 20 minutes.

This is shown within 1 minute of starting the app:
![Screen Shot 2020-02-14 at 3 29 15 PM](https://user-images.githubusercontent.com/8230144/74576587-558c9800-4f40-11ea-8e6b-045c4b30b025.png)

This is shown later: for me it took ~10mins, but I've heard it can take up to 30 mins from others.
![Screen Shot 2020-02-14 at 3 36 43 PM](https://user-images.githubusercontent.com/8230144/74576590-58878880-4f40-11ea-8ab8-01d4e15c8501.png)

@mslipper - we discussed this offline a few minutes ago; let me know if you need other info.

**Comment by mslipper** [comment]
Closed in v0.2.5
