### ISSUE TITLE
Link to hs-airdrop in redeem modal opens inside electron, instead of a new window

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#86]
Expected behavior: open link to hs-airdrop in a new window, like all other links in the app.

Current behavior:
![airdrop-details](https://user-images.githubusercontent.com/8230144/74579923-84f8d000-4f53-11ea-936d-96b6c333f5aa.gif)

**Comment by mslipper** [comment]
Closed in v0.2.6
