### ISSUE TITLE
Inconsistent Display of Auction Details

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#89]
Similar to #82 - likely fixable at the same time.

Note:
- Feb 3rd (this is #82)
- Even though we are not at the release block, it says it is available.
- Even though it says it is available, "Start Auction" is not greyed out.

My thinking is that we should make all of these things consistent.

![Screen Shot 2020-02-15 at 2 40 52 PM](https://user-images.githubusercontent.com/8230144/74596243-589b8d00-5001-11ea-80f8-ffe95a4775a4.png)

**Comment by mslipper** [comment]
Fixed in v0.2.7/
