### ISSUE TITLE
[Suggestion] Bid History should do a better job of clarifying the owner of bids

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#90]
I believe that the current UI implies to users that what we display in Bob is all of the bids, which is concerning because many of them might assume a name has not been bid on, and be surprised when they don't win a name that actually has other bidders.

![Screen Shot 2020-02-15 at 2 43 57 PM](https://user-images.githubusercontent.com/8230144/74596261-a57f6380-5001-11ea-8e73-4959b7aa1f2d.png)

Suggestions:
1. Lowest effort: specify with a header of "Your Bids" instead of "Bid History", and make some copy/tooltip changes to be consistent with that.
2. Link out to hnscan for the name, so people can see other bids.
3. Implement the ability to see other bids directly in Bob, and leave the headers/copy as-is.

**Comment by mslipper** [comment]
Fixed in v0.2.7.
