### ISSUE TITLE
[Suggestion] Once a transaction has been sent, create a link to HNScan

### ISSUE THREAD

**Issue by smcki012** [kyokan/bob-wallet#91]
## Current Behavior
![img](https://i.imgur.com/xSNr3Ru.png)
Once you send a transaction, there is a confirmation page. But, there is no link to for the user to click and see their pending transaction on HNScan. This would make it so the user doesn't have to hop back to their transactions page to open it up quickly in a browser window (as most do).

## Suggested Behavior
Add a link under the confirmation text "To see your transaction on HNScan, click here[]."

Note: This is a fantastic wallet, and I look forward to using it more as it continues to improve. Incredible work.

**Comment by mslipper** [comment]
Fixed in v0.2.7.
