### ISSUE TITLE
[Q] "Set Reminder" Doesn't Do Anything?

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#94]
Not sure if this is intended - suggest we remove or complete this feature.

![set-reminder](https://user-images.githubusercontent.com/8230144/74772216-70168800-5244-11ea-8681-7ce14cedc408.gif)

**Comment by smcki012** [comment]
Set reminder could potentially send an email/text based reminder to the user to compete a bid?

**Comment by mslipper** [comment]
Removed in v0.2.7.
