### ISSUE TITLE
Change reference date for GitHub-follower-count cut-off to 2019-02-04

### ISSUE THREAD

**Issue by skynode** [kyokan/bob-wallet#96]
Based on the latest information from [hs-airdrop](https://github.com/handshake-org/hs-airdrop), the correct cut-off date for accessing HNS based on 15 or more followers is actually 2019-02-04  (not sure if this is February 4th 2019 or April 2nd 2019) but it is definitely no longer 2018-08-27 (clearly August 27th 2018) as is currently shown on the Windows version of the wallet. See the red highlighted area in the image below:

![image](https://user-images.githubusercontent.com/17997010/75390035-ddcb4f80-58e7-11ea-8ff9-78405e71b30f.png)

**Comment by mslipper** [comment]
Fixed in v0.2.7.
