### ISSUE TITLE
[Suggestion] Support for multiple wallets/ledger

### ISSUE THREAD

**Issue by smcki012** [kyokan/bob-wallet#97]
## Suggestion

A Telegram user (Cassandra Shi) suggested support for multiple wallets at once, so users don’t have to logout and import other phrases, which eventually can cause issues like WatchOnly addresses filling up and forcing a rm rf of the application data (this happened to me personally). 

Also, native support for utilizing a ledger with the app similar to MyCrypto would be excellent as well.

**Comment by rithvikvibhu** [comment]
Multiple wallets have been added with #233 and available since Oct 2020.
Ledger support is also added with #344.
