### ISSUE TITLE
Fix error confirming seed phrase 

### ISSUE THREAD

**Issue by phaymond** [kyokan/bob-wallet#98]
Multiple times using `Bob-0.2.6.dmg` I copied the seed phrase correct only for the program to shake and tell me it's wrong. 

I figured out you can't have a space after the last word. This needs to be fixed to provide a better user experience. Thank you!

**Comment by mslipper** [comment]
Fixed in v0.2.7.

**Comment by phaymond** [comment]
Thanks Matthew
