### ISSUE TITLE
Pending Transaction Prevents Coins Being Spendable

### ISSUE THREAD

**Issue by bbjunaid** [kyokan/bob-wallet#99]
My transaction has been pending for ages, and prevents me from spending those coins.

## Expected Behavior

Transaction should complete or fail.

## Current Behavior

Stuck in pending stage.

## Steps to Reproduce

1.
1.
1.
1.

## Screencap

<img width="989" alt="Screen Shot 2020-03-05 at 4 08 21 PM" src="https://user-images.githubusercontent.com/1175122/76131662-207adf00-5fee-11ea-966b-2e99290a0465.png">

**Comment by pinheadmz** [comment]
1. Follow this guide to learn how to use CLI commands with Bob:

https://forum.kyokan.io/t/guide-using-the-handshake-cli-with-bob/21

2. Execute the `zap` command:

https://hsd-dev.org/api-docs/?shell--cli#zap-transactions

The wallet will remove all pending transactions older than the age given on the command line.

Example:

`hsw-cli --id=allison --api-key=<YOUR BOB API KEY> --account=default --age=10 zap`

**Comment by mslipper** [comment]
Closing in favor of #106.
